### ISSUE TITLE
Support for SSL client cert auth

### ISSUE THREAD

**Issue by rtbellows** [skeema/skeema#130] opened 2020-05-27 19:17 UTC
It would be great to be able to use ssl client certs for skeema. Example entry from a user's .my.cnf file:

```
[client]
ssl_ca=/path/to/ca_cert.pem
ssl_cert=/path/to/client_cert.pem
ssl_key=/path/to/private.key
```

**Comment by evanelias** [comment] 2020-05-27 20:37
Thank you for the feature request! I agree this would be useful and plan on offering a solution in a couple months.

**Comment by evanelias** [comment] 2020-06-06 22:47
One clarification I should mention for other readers: if you just want to use encrypted connections, but without specifying a client cert, this is actually supported already via [connect-options](https://github.com/skeema/skeema/blob/master/doc/options.md#connect-options) -- it's just not documented or enabled by default yet. To enable SSL in this manner, use `connect-options="tls=skip-verify"`.

This allows Skeema to connect using a mysql user account created with `REQUIRE SSL`, or a mysql server configured with `require_secure_transport=ON`.  I'll look into making this work by default in the next release.

Stricter cases requiring a valid client cert, such as mysql user accounts created with `REQUIRE X509` / `REQUIRE ISSUER` / `REQUIRE SUBJECT` / `REQUIRE CYPHER`, are not supported yet; that's the focus of this issue.

**Comment by cbcmd** [comment] 2020-07-15 20:35
Hey @evanelias, 

First of all, I wanted to thank you for all the hard work, `skeema` is a truly awesome tool. 

Unfortunately this issue is a hard blocker for my companies' adoption of skeema. We are currently leveraging GCP's `CloudSQL`, which until recently could only be accessed on a public IP. Because of this, we mandated [SSL](https://cloud.google.com/sql/docs/mysql/authorize-ssl#enforcing_ssltls_encryption) for all connections. 

Is this an issue I could help with? A quick skim of the source code suggests that the change needs to be made to the `tengo` dependency first. Should I create an issue there?

**Comment by evanelias** [comment] 2020-07-15 20:49
Hi @cbcmd, thank you for the kind words. To confirm an important point, are you using SSL/TLS specifically with *client-side certs*, and your MySQL users are configured with one or more of `REQUIRE X509` / `REQUIRE ISSUER` / `REQUIRE SUBJECT` / `REQUIRE CYPHER`?

Just to be completely clear, Skeema already fully supports usage of *encrypted connections* and *server-side certs*, including MySQL users configured with `REQUIRE SSL`. This now works by default as of [Skeema v1.4.4](https://github.com/skeema/skeema/releases/tag/v1.4.4), but could also be manually enabled in previous releases.

Support for *client-side* certs would require modifications to both `skeema/skeema` and `skeema/tengo`. The initial support would be straightforward (the driver supports it), but most of the complexity is in the new Skeema configuration options that would need to be added, as well as the test suite coverage. For those reasons I'm hesitant to open up this issue to external contribution, as it would require quite a bit of coordination time.

**Comment by cbcmd** [comment] 2020-07-15 21:13
Confirmed. We require the ability to pass client-side certs to the CloudSQL instance. 

I also believe we will need a `server-name` configuration. This is used when registering a TLS config (unless you want to set `InsecureSkipVerify`, but that's only recommended for testing):

```go
rootCertPool := x509.NewCertPool()
pem, err := ioutil.ReadFile("/path/server-ca.pem")
if err != nil {
    log.Fatal(err)
}
if ok := rootCertPool.AppendCertsFromPEM(pem); !ok {
    log.Fatal("Failed to append PEM.")
}
clientCert := make([]tls.Certificate, 0, 1)
certs, err := tls.LoadX509KeyPair("/path/client-cert.pem", "/path/client-key.pem")
if err != nil {
    log.Fatal(err)
}
clientCert = append(clientCert, certs)
mysql.RegisterTLSConfig("custom", &tls.Config{
    RootCAs: rootCertPool,
    Certificates: clientCert,
    ServerName: "<server-name>",
})
db, err := sql.Open("mysql",
        "<user>:<password>@tcp(<cloud sql instance ip>:3306)/<database>?tls=custom")
```

**Comment by cbcmd** [comment] 2020-07-15 21:20
I understand not wanting to open this up for external contribution. It seems like there is quite a bit of ramp up required to successfully add the feature. 

As I think more about it, I think I can unblock myself by using [CloudSqlProxy](https://cloud.google.com/sql/docs/mysql/sql-proxy). The proxy could handle authentication / TLS, and then I can point skeema at the local UDS. This adds more moving parts, but should tide us over until you're able to add the feature.

**Comment by evanelias** [comment] 2020-07-15 22:41
Thanks, good idea, using a proxy sounds like a solid work-around for now.

Server name validation will likely be included whenever this is finally implemented. It's fairly rare in practice though -- basically it prevents MITM attacks, which aren't normally a major concern since DBs tend to be accessed on private networks. I could see it making sense for the GCP CloudSQL use-case though if CloudSQL requires use of a public IP.

**Comment by rtbellows** [comment] 2021-08-12 21:18
Any update on this FR?

**Comment by evanelias** [comment] 2021-08-12 21:40
It's on the list of [planned/upcoming Premium features](https://www.skeema.io/blog/2021/07/01/premium-cli/#upcoming-features), hopefully will make it into v1.6.0-premium in a few months, but no promises.

**Comment by evanelias** [comment] 2021-09-22 03:17
Update: this functionality will definitely be in v1.6.0-premium. Release target is early November, but subject to change.

These new options are included:

* `ssl-cert` and `ssl-key` -- client-side certs for auth, permits connecting to accounts that have `REQUIRE X509` / `REQUIRE ISSUER` / `REQUIRE SUBJECT` attributes
* `ssl-ca` -- supply a certificate authority file, for verifying the server / MITM protection
* `ssl-mode=verify_ca` -- verify server cert but without strict hostname check
* `ssl-mode=verify_identity` (or equivalently `ssl-verify-server-cert=true` for compat with older `mysql` client or MariaDB `mysql` client) -- verify server including strict hostname check for better MITM protection
* `server-public-key-path` -- improves security and performance of *un*encrypted connections in recent versions of MySQL

These options have all been designed to mimic the exact behavior of the corresponding options in the standard `mysql` client. This way, if you already have them configured in ~/.my.cnf, they'll seamlessly work as-is in Skeema.

Once v1.6.0-premium is released, I'll comment again and will close this issue at that time.

**Comment by evanelias** [comment] 2021-11-11 21:37
[Skeema Premium CLI v1.6.0](https://www.skeema.io/download/) has been released today, including full support for client-side certs via the new options mentioned in my [previous comment](https://github.com/skeema/skeema/issues/130#issuecomment-924548007) :)

**Closed by evanelias** 2021-11-11 21:37 UTC
Labels: feature request
