### ISSUE TITLE
Windows: Unable to use 'skeema init'

### ISSUE THREAD

**Issue by mwhouser** [skeema/skeema#107] opened 2019-10-15 23:40 UTC
I compiled Skeema using Go 1.13.1 on Windows using:

```
go get -u github.com/skeema/skeema
```

When I execute:

```
D:\skeema>skeema init -h myhost -u myuser -p -d schemas
```

I receive the following error:

```
Enter password:
2019-10-15 19:23:57 [ERROR] Unable to use directory D:\skeema/schemas: Unable to write to
                            D:\skeema/schemas/D:\skeema\schemas\.skeema: Unable to write to
                            D:\skeema/schemas/D:\skeema\schemas\.skeema: open
                            D:\skeema/schemas/D:\skeema\schemas\.skeema: The filename, directory name, or volume label
                            syntax is incorrect.
```

Skeema creates the `D:\skeema/schemas/` directory, but it's empty after the error.

I tried both as a normal user and administrator.

**Comment by evanelias** [comment] 2019-10-15 23:47
Sorry but running Skeema natively on Windows is not supported yet, as mentioned in https://github.com/skeema/skeema/blob/master/README.md#status. I have heard it runs properly under WSL, as well as in a Docker container, so those may be possible solutions for now.

I don't currently have a Windows machine, so a native Windows port will require either a corporate sponsor or a third-party code contribution.

Closing this since it's a duplicate of #14.

**Closed by evanelias** 2019-10-15 23:47 UTC
Labels: duplicate, not a bug

**Comment by evanelias** [comment] 2021-07-06 18:46
I'm happy to announce that the Premium edition of the Skeema CLI, including a native Windows exe build, is now available! Learn more at the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
