### ISSUE TITLE
MariaDB: SSL error / cannot connect with Skeema v1.4.4

### ISSUE THREAD

**Issue by obissick** [skeema/skeema#135] opened 2020-06-26 19:48 UTC
tls: failed to parse certificate from server: asn1: syntax error: invalid boolean

**Comment by evanelias** [comment] 2020-06-26 20:02
Thank you for the report, and sorry to hear this. Can you please provide more context on MySQL version/flavor, Skeema configuration, Skeema version, and the command invocation that is returning this? Is the MySQL user configured with REQUIRE SSL?

**Comment by obissick** [comment] 2020-06-26 20:10
Using MariaDB 10.4
So the user must be set to REQUIRE SSL for it to work?

**Comment by evanelias** [comment] 2020-06-26 20:39
Thanks, a few follow-up questions to help track this down:

> MariaDB 10.4

Ah, so it appears that MariaDB doesn't ship with SSL enabled out-of-the-box, unlike mainline MySQL or Percona Server. Unfortunately that means Skeema's automated test suite isn't actually covering the use-case of SSL-on-MariaDB :(

What's the full version number please, e.g. 10.4.13. I'll try to reproduce against the specific point release sometime this weekend.

Also just to confirm, is Skeema connecting directly to MariaDB, or is there a proxy (ProxySQL, MaxScale, etc) in between? 

> latest Skeema version

Downloaded from https://github.com/skeema/skeema/releases, or compiled from source? If compiled from source, which version of Golang?

> connect-options=tls=skip-verify

If you remove this from your config, is Skeema able to connect? As of Skeema v1.4.4 the default is `tls=preferred` which should use unencrypted connections as a fallback for servers where SSL is disabled.

If you still get errors without any connect-options, you could try `connect-options=tls=false` for now to disable SSL connections as a temporary work-around, which should match the behavior of pre-v1.4.4 versions of Skeema.

> So the user must be set to REQUIRE SSL for it to work?

No, just wanted to get more info on how the mysql user's SSL was configured, to help in trying to reproduce this :) Thanks again!

**Comment by obissick** [comment] 2020-06-26 20:45
Yes 10.4.13, connecting directly to server, no LB or Proxy, doesnt work with or without the tls option, works with `connect-options=tls=false`

**Comment by evanelias** [comment] 2020-06-27 23:27
Unfortunately I was unable to reproduce this on MariaDB 10.4.13 so far. After configuring the server to use a self-signed cert, Skeema was able to connect correctly using SSL.

Two follow-up questions please:

1. Did you download Skeema from https://github.com/skeema/skeema/releases, or did you compile Skeema from source? If compiled from source, which version of Golang did you use to compile it?

2. Can you verify that the mysql/mariadb command-line client is able to connect to your server using SSL? For example,
```
mysql ... --ssl -e status | grep SSL
```
Replace `...` with your normal connectivity options like -h hostname etc.

If the connection is successfully using SSL, you should see output like this:
```
SSL:			Cipher in use is TLS_AES_256_GCM_SHA384
```
Cipher may vary, please let me know what it says. Thanks!

**Comment by obissick** [comment] 2020-06-29 15:09
> Unfortunately I was unable to reproduce this on MariaDB 10.4.13 so far. After configuring the server to use a self-signed cert, Skeema was able to connect correctly using SSL.
> 
> Two follow-up questions please:
> 
> 1. Did you download Skeema from https://github.com/skeema/skeema/releases, or did you compile Skeema from source? If compiled from source, which version of Golang did you use to compile it?
> 2. Can you verify that the mysql/mariadb command-line client is able to connect to your server using SSL? For example,
> 
> ```
> mysql ... --ssl -e status | grep SSL
> ```
> 
> Replace `...` with your normal connectivity options like -h hostname etc.
> 
> If the connection is successfully using SSL, you should see output like this:
> 
> ```
> SSL:			Cipher in use is TLS_AES_256_GCM_SHA384
> ```
> 
> Cipher may vary, please let me know what it says. Thanks!

**Comment by obissick** [comment] 2020-06-29 15:10
1. Yes i downloaded it from the releases.
2. Got the correct response from the command. `SSL:			Cipher in use is DHE-RSA-AES256-GCM-SHA384`

**Comment by evanelias** [comment] 2020-06-29 21:28
Thanks! Any chance you know how the server's cert was originally generated?

The only things I could find regarding this error suggest it occurs with certs generated via MatrixSSL, which used a different/unusual representation of boolean true values. Apparently GoLang [does not support that cert format](https://github.com/golang/go/issues/11091) since it is very rare. I found that issue via https://github.com/zmap/zgrab/issues/180 which mentions the same error.

I had hoped there was an option in OpenSSL to generate certs in this format, to try to reproduce the problem, but I haven't been able to find one.

**Comment by obissick** [comment] 2020-06-30 16:37
I generated it using OpenSSL, i think it has something to do with the certs. I tried it on a different server and it worked. I will recreate certs and try again. Thanks.

**Comment by evanelias** [comment] 2020-07-01 14:25
Glad to hear it's working fine with other certs. I'll close this for now, but please feel free to reopen if you find that some particular combination of openssl options generates another cert that consistently reproduces the problem. If there's a reproducible test case, then we can file a bug with the Golang maintainers. Thanks!

**Closed by evanelias** 2020-07-01 14:25 UTC

**Comment by obissick** [comment] 2020-07-06 17:11
Definitely was a cert issue, works fine now.
