### ISSUE TITLE
not enough arguments in call to logrus.IsTerminal

### ISSUE THREAD

**Issue by MACscr** [skeema/skeema#4] opened 2017-05-09 07:56 UTC
Can't seem to install Skeema.

```
webusr@id-dev:~$ export GOPATH=$HOME/go
webusr@id-dev:~$ export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
webusr@id-dev:~$ go get github.com/skeema/skeema
# github.com/skeema/skeema
go/src/github.com/skeema/skeema/log.go:13: not enough arguments in call to logrus.IsTerminal
```

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
```

```
webusr@id-dev:~$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by evanelias** [comment] 2017-05-09 13:10
Thank you for the report! I'm investigating and will try to reproduce. First though, what version of Go are you using? (output of `go version`)

Skeema uses frozen vendored dependencies, so changes in upstream dependencies should not break the build. But support for vendored deps in Go is only enabled by default in Go 1.6 (feb 2016) or newer. In Go 1.5 you can also enable it via GO15VENDOREXPERIMENT=1 env var before running any `go` command. It isn't supported in Go 1.4 or older. Also not sure about gccgo, as I've only tested using the official Golang toolchain so far.

I'll investigate more tonight on my end. In any case I'll update Skeema's README to indicate the Golang version assumptions. I also plan to create a formal release of Skeema 0.2, including prebuilt binaries for macOS and Linux, within the next few weeks.

Thanks again for the report, and for trying out Skeema!

**Comment by MACscr** [comment] 2017-05-09 17:20
`root@id-dev:~# apt-get install golang-go
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  golang-go-linux-amd64 golang-src
Recommended packages:
  golang-go.tools
The following NEW packages will be installed:
  golang-go golang-go-linux-amd64 golang-src
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.1 MB of archives.
After this operation, 159 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://http.us.debian.org/debian/ jessie/main golang-src amd64 2:1.3.3-1 [5,149 kB]
Get:2 http://http.us.debian.org/debian/ jessie/main golang-go-linux-amd64 amd64 2:1.3.3-1 [7,918 kB]
Get:3 http://http.us.debian.org/debian/ jessie/main golang-go amd64 2:1.3.3-1 [9,030 kB]
Fetched 22.1 MB in 8s (2,742 kB/s)
Selecting previously unselected package golang-src.
(Reading database ... 36263 files and directories currently installed.)
Preparing to unpack .../golang-src_2%3a1.3.3-1_amd64.deb ...
Unpacking golang-src (2:1.3.3-1) ...
Selecting previously unselected package golang-go-linux-amd64.
Preparing to unpack .../golang-go-linux-amd64_2%3a1.3.3-1_amd64.deb ...
Unpacking golang-go-linux-amd64 (2:1.3.3-1) ...
Selecting previously unselected package golang-go.
Preparing to unpack .../golang-go_2%3a1.3.3-1_amd64.deb ...
Unpacking golang-go (2:1.3.3-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up golang-src (2:1.3.3-1) ...
Setting up golang-go-linux-amd64 (2:1.3.3-1) ...
Setting up golang-go (2:1.3.3-1) ...
root@id-dev:~# go version
go version go1.3.3 linux/amd64
root@id-dev:~#`

**Comment by evanelias** [comment] 2017-05-10 03:12
Ah yes, unfortunately Go 1.3.3 is rather out-of-date. Go 1.3 came out three years ago, and does not yet support vendored dependencies. What this means is that for all third-party libs that Skeema depends on, in Go <1.6, `go get` will fetch those libs from master, rather than using the specific frozen versions of the libs bundled with Skeema.

Anyway, I've just updated Skeema in commit 8ef8ea to use the latest version of logrus. Please try re-compiling and let me know if that fixed it? The root cause was that logrus recently made a backwards-incompatible API change in https://github.com/sirupsen/logrus/commit/1726e1. Hopefully, logrus is the only dep that's had a recent breaking change, but I am not certain. I won't normally be able to provide support for Go pre-1.6 as it's a bit of headache.

That all said -- I plan to do a formal release within the next 2-3 weeks, and will offer prebuilt bins for Linux and macOS at that time. That avoids any risk of old compilers :)

Thanks again for the report, it's much appreciated! I've updated Skeema's README to list the min Golang version. Closing this out, but please re-open if you encounter any compilation issues with Go 1.6+. Totally understand if you just prefer to wait for the prebuilt bins though too!

**Closed by evanelias** 2017-05-10 03:12 UTC
