### ISSUE TITLE
Error during skeema init (procedure)

### ISSUE THREAD

**Issue by varadz** [skeema/skeema#159] opened 2021-02-23 21:17 UTC
I am getting an error during "skeema init". Processing stops once I hit this error, and it does not seem I can exclude procedures using "--ignore-table" option.

As I look at the procedure SQL, it does seem that it contains "\" escape characters in the text.
It would be great to have an option to skip some stored procedures during the init, similarly as we do with the tables.

 The error we receive:
2021-02-23 14:08:39 [ERROR] procedure `xxxxxxxxxxx` is unexpectedly not able to be parsed by Skeema
                            Please file an issue report at https://github.com/skeema/skeema/issues/new with
                            this information:
                            Error value=<source>:15:31: invalid token '\\'
2021-02-23 14:08:39 [ERROR] Unfortunately this error is fatal and prevents Skeema from being usable in your
                            environment until this is resolved.

**Comment by evanelias** [comment] 2021-02-23 22:06
Thank you for the bug report!

Backslashes should already work properly inside of quoted strings (and appear to be fine when I test), and I can't seem to think of an example of how they would be used outside of a string. Can you explain more about how the backslash character is used in your proc body? If it's only used inside of strings, is there anything unusual about those strings?

Also just for background info, what database vendor/version/OS are you using? (e.g. "MySQL 8.0.19 running on Linux", "MariaDB 10.5.8 on AWS RDS", etc)

> It would be great to have an option to skip some stored procedures during the init, similarly as we do with the tables.

Would that be useful just because of this Skeema bug, or do you have other use-cases where ignoring a proc/func would be beneficial? Thanks!

**Comment by varadz** [comment] 2021-02-24 02:31
Thank you very much for a great product and your support! 

We use Percona MySQL 5.7.29-32 running on Linux.

I believe this dummy proc body will help to reproduce the error during "skeema init"

DROP PROCEDURE IF EXISTS test;
CREATE PROCEDURE `test`(IN param1 mediumtext)
BEGIN
SET @query = CONCAT('SELECT DISTINCT col0,
            col1, col2,
            IF(col3 = \'NULL\' OR cal3 = \'<unset/>\', \'NULL:unset\', col3) AS new_value,
            .....
            .....
            ', ')');
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;                    
END;

I would think that function to exclude procedures/functions would be in line with the existing functionality to exclude schemas and tables. This would certainly help me to work around the issue. 


One more comment:
Today, different object types are all lumped under the same directory, and it is hard to locate the specific object type when a database is large. 
It would be great if skeema could store objects of different type under different directories:
<database_name>/<object_type>/<object_name>.sql
for example:
<database_name>/tables/ table1.sql
<database_name>/procedures/procedure1.sql

**Comment by evanelias** [comment] 2021-02-24 03:58
Afraid that example doesn't reproduce the error on my end... `skeema init` works successfully with that exact proc body on skeema 1.4.7 on percona server 5.7 :(

The error message is saying the problem wasn't hit until line 15 of your real proc. Anything particularly weird on that line involving multiple levels of nested/escaped quotes?

It's also possible that GitHub markdown is mangling the example. If you are able to share the actual full proc body privately, please email -- address is shown on https://github.com/skeema/ as long as you're logged in to github. Thanks!

> I would think that function to exclude procedures/functions would be in line with the existing functionality to exclude schemas and tables

Sure, but that's more in the "nice to have" category, which isn't exactly high priority relative to other possible features :) That said, feel free to open a feature request issue, as it might be a good candidate for a third party pull request. The ignore-schema and ignore-table options were actually originally provided by a [pull request](https://github.com/skeema/skeema/pull/15).

> It would be great if skeema could store objects of different type under different directories

Unfortunately that would be a very large change, as much of the current logic assumes 1 dir = 1 logical schema. Support for procs/funcs was generously sponsored by a company, and they were ok with everything going in one dir, so that's how it was implemented. Multiple levels of dirs may be supported some day in the future, but perhaps only in the commercial edition of Skeema, given how time-consuming it would be to implement.

**Comment by varadz** [comment] 2021-02-24 05:45
Thank you for looking into this.
I shared the full procedure body privately by email.
Ditto on feature request issue and support on directories!

**Comment by evanelias** [comment] 2021-02-24 16:58
Awesome, thank you! I was able to reproduce the bug and found the cause. I should have a fix ready later today and will post an update comment then.

**Comment by evanelias** [comment] 2021-02-24 21:53
This one was subtle: the bug only comes up if you have a `--` style comment immediately followed by a newline (that is, "--\n"), and then the following line of the proc/func contains the start of a multi-line string, which then later contains non-operator characters such as backslashes on subsequent lines.

A fix has been committed to the main branch, and will be included in the upcoming release of Skeema v1.5.0. Thank you for the bug report!

Longer detailed explanation of the bug:

The root cause was a mistake in a regex in Skeema's statement lexer. Although Skeema [does not rely on SQL parsing](https://www.skeema.io/docs/faq/#no-reliance-on-sql-parsing) to understand tables/procs/funcs, it still does enough parsing to identify the statement type and object name. This way `skeema pull` is able to update the correct part of a file containing multiple statements; `skeema lint` is able to annotate the correct statement; etc. When this parser fails, it's treated as a fatal error because it prevents Skeema from properly associating the proc in your .sql file with the corresponding proc in your database at all, rendering a diff impossible.

MySQL handles `--` style comments in a slightly nonstandard way: they must be [followed by whitespace](https://dev.mysql.com/doc/refman/8.0/en/ansi-diff-comments.html) to be treated as a comment. The intended handling of this for Skeema's lexer is essentially "if `--` followed by whitespace is encountered, treat this as a comment until the end of this line". However, in the case of "--\n", the regex incorrectly treated the comment as extending to the *following* line's newline.

In most cases this actually doesn't break anything, because this parser doesn't affect Skeema's introspection or execution of individual statements; in other words, this bug can't ever cause random lines of procs/funcs to be omitted. However, in one specific case it can cause the lexer to fail with a fatal error: if the line after the comment contains the beginning of a multi-line string, the lexer would "miss" the beginning of the string, and then error upon encountering subsequent lines with characters that aren't allowed to appear outside of strings (for example, a backslash, since that isn't a valid operator in mysql).

**Closed by evanelias** 2021-02-24 21:53 UTC
Labels: bug

**Comment by evanelias** [comment] 2021-02-25 23:55
This fix has been included in today's release of [Skeema v1.5.0](https://github.com/skeema/skeema/releases/tag/v1.5.0). Thanks again for the bug report!

**Comment by varadz** [comment] 2021-02-26 02:27
Thank very much for the excellent support!
