### ISSUE TITLE
Skeema fails to create a spatial index on push, even though it can read and pull it.

### ISSUE THREAD

**Issue by VanTanev** [skeema/skeema#214] opened 2023-05-11 20:14 UTC
**Describe the bug**
Skeema fails to create a spatial index on push, even though it can read and pull it.

**Environment**
- Skeema version: *1.10.0-plus, licensed to Holibob*
- Database vendor, version, OS/platform: *AWS Aurora MySQL 8.0*

**To Reproduce**
Skeema successfully pulled this table from our database, but then fails to push it:
```sql
CREATE TABLE `GeoCoordinate` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `geoCoordinate` point NOT NULL COMMENT 'The geo location coordinates',
  PRIMARY KEY (`id`),
  SPATIAL KEY `GeoCoordinate_geoCoordinate_idx` (`geoCoordinate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

When trying to push:
```bash
➜  skeema diff cypress --debug
2023-05-11 23:08:36 [INFO]  Using container skeema-mysql-8.0 (image=mysql/mysql-server:8.0) for workspace operations
2023-05-11 23:08:43 [INFO]  Generating diff of cypress.database:3306 holibob vs
                           /master/database-scripts/skeema/holibob/*.sql
2023-05-11 23:08:47 [WARN]  Skipping table `GeoCoordinate`: Skeema does not support generating a diff of this table. Use --debug to see which properties of
                            this table are not supported.
2023-05-11 23:08:47 [DEBUG] The desired state ("to" side of diff) contains unexpected or unsupported clauses in SHOW CREATE TABLE.
                            --- desired state expected CREATE
                            +++ desired state actual SHOW CREATE
                            @@ -42 +42 @@
                            -  SPATIAL KEY `GeoCoordinate_geoCoordinate_idx` (`geoCoordinate`(32))
                            +  SPATIAL KEY `GeoCoordinate_geoCoordinate_idx` (`geoCoordinate`)

2023-05-11 23:08:48 [INFO]  cypress.database:3306 holibob: diff complete

2023-05-11 23:08:48 [INFO]  Stopping container skeema-mysql-8.0
2023-05-11 23:08:50 [WARN]  Skipped 1 operation due to unsupported feature
2023-05-11 23:08:50 [DEBUG] Exit code 1
```

**Expected behavior**
We would expect if skeema can pull a database it should then be able to push it.

**Comment by VanTanev** [comment] 2023-05-11 20:18
If we don't use docker workspace we get a similar error with a slightly different index size:
```bash
2023-05-11 23:17:01 [DEBUG] The desired state ("to" side of diff) contains unexpected or unsupported clauses in SHOW CREATE TABLE.
                            --- desired state expected CREATE
                            +++ desired state actual SHOW CREATE
                            @@ -42 +42 @@
                            -  SPATIAL KEY `GeoCoordinate_geoCoordinate_idx` (`geoCoordinate`(26))
                            +  SPATIAL KEY `GeoCoordinate_geoCoordinate_idx` (`geoCoordinate`)
```

**Comment by evanelias** [comment] 2023-05-11 20:32
Sorry, Skeema isn't able to diff tables containing spatial indexes yet. Please see https://www.skeema.io/docs/requirements/#unsupported-for-alter-table

Closing as a duplicate of #97, but will consider this as a +1 on that for prioritization purposes.

**Closed by evanelias** 2023-05-11 20:32 UTC
Labels: bug

**Comment by VanTanev** [comment] 2023-05-11 20:34
Is there any workaround we can apply so only the spatial index is ignored by skeema, or that's not possible?

**Comment by evanelias** [comment] 2023-05-11 20:37
The general workaround for unsupported-for-diff cases is to just ALTER these tables outside of Skeema (e.g., direct invocation of ALTER TABLE manually, or pt-online-schema-change, etc). Afterwards, you can update your schema repo using `skeema pull`, which will work properly even on unsupported tables.

The only other option is to ignore this table in Skeema entirely by using ignore-table.

**Comment by VanTanev** [comment] 2023-05-11 20:54
We're in an awkward position, as not having this index makes one of our endpoints extremely slow, while removing the table from skeema breaks our development and e2e environments (they stand up fully isolated databases using skeema). 

At the same time, we understand this is not a high-priority feature for you.

**Comment by evanelias** [comment] 2023-05-11 21:44
The usual workaround is to just ALTER it everywhere outside of Skeema. After that, generally everything should work fine once the .sql filesystem definition and the database definition match again. `skeema diff` and `skeema push` will only complain about this table if there's an actual difference; and even then, it's a warning, not a fatal error. And these commands can CREATE the table just fine, for example if you're pushing to an initially-empty e2e environment, that should work even if the spatial index is in the definition.

That said, I could see this workaround getting annoying if it's a table that you otherwise need to ALTER often in other ways. In that case yeah I think the best bet may be what you landed on, using ignore-table just in certain environments (or equivalently via command-line overrides), but if so you should be able to safely include the index in the filesystem definition.

re: prioritization, this definition increases it, but realistically it'll be a few months minimum.

**Comment by VanTanev** [comment] 2023-05-12 08:04
@evanelias The unfortunate thing is that `skeema push` now returns exit status 1 even on creating tables, because of the warning for the skipped table, which broke all our automation scripts. I'm probably going to need to grep output for `[ERROR]` to be able to differentiate it from real errors. A `[WARN]` should probably not result in `exit 1`?

**Comment by VanTanev** [comment] 2023-05-13 09:30
Thank you for your guidance!

**Comment by evanelias** [comment] 2023-06-20 21:28
Minor update: Skeema v1.10.1 is now available ([release notes](https://github.com/skeema/skeema/releases/tag/v1.10.1)) and it improves the situation a bit with unsupported tables. Now Skeema can often generate an ALTER for an existing unsupported table, as long as the modification doesn't touch the unsupported features.

For example, if a pre-existing table already happens to have a spatial index, you can now use Skeema to add columns to the table, add a normal index to the table, etc. You just can't add a new spatial index to a table -- that still requires doing the change outside of Skeema and then running `skeema pull` to update the .sql file.

That all said, adding full support for spatial indexes is pretty high on the priority list, hopefully in Q3.

**Comment by VanTanev** [comment] 2023-06-20 21:46
Love to see it!
