### ISSUE TITLE
Errors when DB hosted on MacOS or Windows, if schema/table names have uppercase chars

### ISSUE THREAD

**Issue by biszinc** [skeema/skeema#65] opened 2019-03-20 16:47 UTC
Hi Guys,

We ran into a problem using skeema push to update a development environment.   The environment already has the database setup using skeema, we are trying to deploy an update.  when we run push.  we got the error complaining the database already exists and ignore all the following changes.     I wonder if anyone have seem this issue or got any tips in solving this problem?   Many thanks in advance.

CREATE DATABASE BZ_main CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
2019-03-20 19:02:28 [ERROR] Error running DDL on dataserver:3306 BZ_main: Error 1007: Can't create database 'BZ_main'; database exists
2019-03-20 19:02:28 [WARN]  Skipping 25 remaining operations for dataserver:3306 BZ_main due to previous error
2019-03-20 19:02:28 [INFO]  dataserver:3306 BZ_main: push complete

**Comment by evanelias** [comment] 2019-03-20 19:04
Thanks for trying out Skeema! I haven't seen this problem before, but my first guesses would be either something relating to permissions of the mysql user that you're using in Skeema, or perhaps an issue with a case-insensitive filesystem.

A few questions to help debug:
* Are you running Skeema with a non-root mysql user? If so, what permissions does that user have?
* On the database server side, for the dev db where you're hitting this problem, what vendor (MySQL vs Percona vs MariaDB) and version are you using? What operating system?
* What host are you running `skeema` from, and what operating system?
* Any special Skeema settings in-use, either on the command-line or in a `.skeema` option file?
* What output does `skeema diff` show?
* What output does `skeema lint` show?

Thanks!

**Comment by biszinc** [comment] 2019-03-22 07:47
Thank you looking into our issue Evan, btw, wonderful work!  You’ve got a great solution here.

 �

We have checked the permission and compared the config of the setup with other env but doesn’t have the problem, and sadly we have failed to find any fix so far.  Our answers to your questions are attached below.    

 �

**Comment by evanelias** [comment] 2019-03-22 17:07
Just to completely rule out a permissions issue, I'd recommend running a diff as root on dev once just to test. You can override user/password via the command-line, e.g. `skeema diff --user root --password` (it'll prompt for password if not supplied directly).

The more likely culprit is a case sensitivity issue, though. Unlike Linux, MacOS uses a case-insensitive filesystem by default, and I notice your database name has a mix of uppercase and lowercase. Can you confirm the casing of "BZ_main" is consistent in all places? e.g. same exact casing when manually running `SHOW DATABASES`, same in your .skeema file, same on your dev db's data directory?

On the database server side, Skeema is tested against 11 different versions of MySQL  / Percona Server / MariaDB, but all are on Linux (noted in the [README](https://github.com/skeema/skeema/blob/master/README.md#status)) since that is far more common than MacOS on the db server side.

As far as I know, there's no "official" MacOS build of MariaDB, which makes testing more complicated. Did you install it via something like Homebrew, or are you using Docker for Mac? If the latter, does the db's filesystem exist only in the container, or are you mapping a directory from your Mac into the container as a volume?

Also re: `skeema lint`, I'm not sure what you mean by the output is "showing everything" -- are there any errors displayed? Thanks!

**Comment by biszinc** [comment] 2019-03-25 15:57
Thank you for the pointer Evan.  

 �

We tried changing the skeema user to root and run the code again, we are getting the same result.   It seems privilege is not the cause of problem…

 �

The error we continue to see is database exists,   I wonder if there’s option in skeema that would allow us skeema to ignore the error and continue?

 �

Regarding to lint, the command return the full schema of every table in the database (forgive me for not being able to post the full result, it’s very long and sensitive).   

 �

Best regards

Tor.

 �

**Comment by evanelias** [comment] 2019-03-25 17:21
Thank you for testing as root to confirm it's not a permissions issue. Given that, I would definitely suspect it's a case-insensitive filesystem issue in this case. 

So far, Skeema fully supports MySQL/PerconaServer/MariaDB **running on Linux**. Other operating systems (on the database server side) have not been tested, and it is entirely possible there are some bugs relating to case-insensitivity and values of the global setting [lower_case_file_system](https://mariadb.com/kb/en/library/server-system-variables/#lower_case_file_system) and [lower_case_table_names](https://mariadb.com/kb/en/library/server-system-variables/#lower_case_table_names) -- especially if using mixed cases in your database or table names (as it seems you are doing).

I would like to debug and fix this, but I really need more info, as per my previous reply:

* Can you confirm the casing (capitalization) of "BZ_main" is consistent in all places? e.g. same exact casing when manually running SHOW DATABASES, same in your .skeema file, same on your dev db's data directory?

* What method of installing/running MariaDB on MacOS are you using? e.g. installing via homebrew, vs running via Docker for Mac. And if using Docker, are you mapping a volume or no? (I'd like to try reproducing this issue on my end, but I need to have a basic idea of how the database is installed/running in order to do that...)

> The error we continue to see is database exists, I wonder if there’s option in skeema that would allow us skeema to ignore the error and continue? 

The only possible work-around that comes to mind is perhaps configuring the database name to be fully lower-case in dev only. For example, in your .skeema file at the schema level, maybe this will work:

```
[production]
schema=BZ_main

[development]
schema=bz_main
```

> Regarding to lint, the command return the full schema of every table in the database

I don't understand what you mean here... `skeema lint` does not output schemas / CREATE statements. It analyzes your schema as it exists *in your .sql files* (by replaying them in a temporary location) but does not otherwise interact with your real schemas that exist *on the actual database*. That's why it may be useful to use in debugging your problem -- if even `skeema lint development` (or whatever you've called the dev environment) is getting an error, that can help isolate which code path is doing the wrong thing in Skeema.

**Comment by biszinc** [comment] 2019-03-25 18:56
Thanks Evan,

 �

My apologies for missing the last 2 questions.  Yes the spelling is consistence, BZ_main is used throughout the solution. (indeed we are only using skeema to deploy/update the database in this env).

 �

The sql server was setup natively, it’s not running under docker. 

 �

I will get a dump of the lint result and send it to you privately in separate email.  And we can certainly try the all lower case as well, keep post the result here.

 �

Many thanks.

Tor.

 �

**Comment by evanelias** [comment] 2019-03-26 15:43
Thanks! No need for full lint output; I'm just curious if any errors were reported (`[ERROR]` in red text) when running lint against the dev environment.

One other thing that might be very helpful -- can you please check the values of global variables `lower_case_file_system` and `lower_case_table_names`? i.e. running a query like this manually:
```sql
SELECT @@global.lower_case_file_system, @@global.lower_case_table_names;
```
Thanks again!

**Comment by biszinc** [comment] 2019-03-29 15:07
Hi Evan,

 �

Sorry it took us a few days, our member got sick for the last couple days.  

 �

I have done a test to try to rename the database to all lower case as you have suggested, I can confirm once we redo the database with all lower case. I can deploy the table and make modification without error.   

 �

I guess this settle the case, we will sort out a alternative setup with the database here,  you have our thanks for your time.

 �

And here’s the answer for the other questions you have

 �

Lint run has no error. Only one warning suggesting one of my table does not have a primary key.

 �

The sql you ask have this output

+---------------------------------+---------------------------------+
| @@global.lower_case_file_system | @@global.lower_case_table_names |
+---------------------------------+---------------------------------+
|                               1 |                               2 |

 �

Best regards

Tor.

 �

 �

**Comment by evanelias** [comment] 2019-03-29 15:48
This is excellent info, thanks! This confirms the root issue is that Skeema does not currently work properly when the database is running on a case-insensitive filesystem (e.g. MacOS or Windows), if some schema names or table names include uppercase characters.

For now I'll retitle this issue and also note the problem in doc/requirements.md. In the near future I'll aim to do more research on how `lower_case_table_names` (which MySQL/MariaDB automatically sets to 1 on Windows and 2 on MacOS) affects the capitalization data shown in `information_schema`, which Skeema relies on querying extensively. Hopefully it should be fixable in Skeema in theory, but I can't estimate how soon.

Thank you again for your patience with all of my debugging questions :)

**Comment by evanelias** [comment] 2022-03-30 21:20
A fix for this issue is finally planned for Skeema v1.8.0, aiming for release in 2-3 months. It will cover the following:

* Mixed-case names, all situations and commands, when the server is using `lower_case_table_names=1` (default on Windows, including Azure Database for MySQL which is Windows-based under the hood). This will be included in comprehensive test suite coverage, since it is possible to enable `lower_case_table_names=1` in our integration suite's Dockerized test databases.
* Mixed-case names for most situations, but not non-InnoDB tables, when the server is using `lower_case_table_names=2` (default on MacOS). This one will need to be tested manually only, as there is no straightforward way to have Dockerized tests use `lower_case_table_names=2`.
* Environments that have a mix of DB server operating systems / `lower_case_table_names` values will generally be supported. Some cases require uniformity though, such as when running `skeema diff` or `skeema push` in a sharded situation, where a single subdir maps to multiple DB shards -- in this situation, Skeema will confirm that all shards have the same value of `lower_case_table_names`, and throw an error if not.

The fix in Skeema v1.8.0 will be present in both Community and Premium editions.

Today's release of [Skeema v1.7.1](https://github.com/skeema/skeema/releases/tag/v1.7.1) actually already includes some of these fixes "early" in the Premium edition, since mixed-case view names were especially problematic with `lower_case_table_names` of 1 or 2. However, until v1.8.0 is released, please consider the support for Windows or MacOS on the db server side to be "best effort" rather than full support, even in Premium.

**Closed** 2022-04-18 19:03 UTC
Labels: bug

**Comment by evanelias** [comment] 2022-06-02 23:13
Happy to say [Skeema v1.8.0 is now available](https://www.skeema.io/blog/2022/06/02/v180-released/) and contains full support for database servers running on any OS or with any server-side `lower_case_table_names` value!

**Comment by evanelias** [comment] 2022-06-07 20:47
Related to this issue: for anyone stumbling over `lower_case_table_names` problems (in Skeema or in general), I just published a [new blog post](https://www.skeema.io/blog/2022/06/07/lower-case-table-names/) providing a deep-dive into `lower_case_table_names` and OS portability / name-case issues, since it's a very common pain point in MySQL and MariaDB!
