### ISSUE TITLE
Generating a diff cannot continue

### ISSUE THREAD

**Issue by xaviclave** [skeema/skeema#194] opened 2022-11-25 15:36 UTC
The tables are identical and it detects them as different and cannot continue

2022-11-25 16:32:15 [WARN] Skipping table `acciones`: Skeema does not support generating a diff of this table. Use --debug to see which properties of this table are not supported.
2022-11-25 16:32:15 [DEBUG] The desired state ("to" side of diff) contains unexpected or unsupported clauses in SHOW CREATE TABLE.
2022-11-25 16:32:15 [DEBUG] --- desired state expected CREATE
2022-11-25 16:32:15 [DEBUG] +++ desired state actual SHOW CREATE
2022-11-25 16:32:15 [DEBUG] @@ -9 +9 @@
2022-11-25 16:32:15 [DEBUG] -) ENGINE=InnoDB DEFAULT CHARSET=utf8
2022-11-25 16:32:15 [DEBUG] +) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci

skeema version 1.8.2-community,

**Comment by evanelias** [comment] 2022-11-25 22:20
You didn't mention your database version, but based on the behavior, I'm guessing you're using a MariaDB point release from earlier this month. MariaDB changed the behavior of `SHOW CREATE TABLE` in their releases this month, breaking compatibility with Skeema.

This has already been fixed in the main branch in f2dcaf8, there just hasn't been a new Skeema release yet. The next release (v1.9.0) should be out in 1-2 weeks.

Closing as duplicate of #193.

If in fact you're not using a MariaDB point release from the past month, please open a new issue, and be sure to fill out the fields from the bug report template. Without that information, it's really impossible to diagnose bugs. Thanks.

**Closed by evanelias** 2022-11-25 22:20 UTC
Labels: bug

**Comment by evanelias** [comment] 2022-12-01 21:35
Skeema v1.9.0 has now been [released](https://www.skeema.io/blog/2022/11/30/v190-released/), and contains this fix.
