### ISSUE TITLE
Generated column expression using LIKE cannot be parsed by Skeema

### ISSUE THREAD

**Issue by jakubkulhan** [skeema/skeema#181] opened 2022-03-02 17:00 UTC
**Describe the bug**

Running `skeema init` results in this error message:

```
2022-03-02 17:53:50 [ERROR] table `notifications` is unexpectedly not able to be parsed by Skeema
                            Please file an issue report at https://github.com/skeema/skeema/issues with this
                            information:
                            Error value=<nil>
2022-03-02 17:53:50 [ERROR] Unfortunately this error is fatal and prevents Skeema from being usable in your
                            environment until this is resolved.
```

`SHOW CREATE TABLE` for the table outputs:

```
CREATE TABLE `notifications` (
  `notification_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `notification_type_id` bigint(20) unsigned NOT NULL,
  `trigger_event_id` binary(26) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone_number` varchar(255) DEFAULT NULL,
  `data` json DEFAULT NULL,
  `text` mediumtext,
  `created_at` datetime NOT NULL,
  `last_attempt_at` datetime DEFAULT NULL,
  `failed_attempts` int(11) DEFAULT NULL,
  `notified_at` datetime DEFAULT NULL,
  `remote_id` varchar(255) DEFAULT NULL,
  `notified_via` enum('EMAIL','SMS','NONE') DEFAULT NULL,
  `did_not_notify_reason` enum('UNSUBSCRIBED','MISSING_MARKETING_CONSENT','NOT_DEV_USER','FAILURE','BOUNCED_USER') DEFAULT NULL,
  `sender_user_id` bigint(20) unsigned DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `delivery_data` json DEFAULT NULL,
  `bounced_at` datetime DEFAULT NULL,
  `bounce_type` enum('PERMANENT_NO_EMAIL','PERMANENT_OTHER','TRANSIENT_MAILBOX_FULL','TRANSIENT_MESSAGE_TOO_LARGE','TRANSIENT_CONTENT_REJECTED','TRANSIENT_ATTACHMENT_REJECTED','TRANSIENT_OTHER') DEFAULT NULL,
  `bounce_data` json DEFAULT NULL,
  `complained_at` datetime DEFAULT NULL,
  `complaint_type` varchar(255) DEFAULT NULL,
  `complaint_data` json DEFAULT NULL,
  `opened_at` datetime DEFAULT NULL,
  `clicked_at` datetime DEFAULT NULL,
  `branch` varchar(255) DEFAULT NULL,
  `subscription_id` bigint(20) unsigned DEFAULT NULL,
  `consent_id` bigint(20) unsigned DEFAULT NULL,
  `cart_id` bigint(20) unsigned GENERATED ALWAYS AS (json_unquote(json_extract(`data`,'$.cartId'))) STORED,
  `delivery_id` bigint(20) unsigned GENERATED ALWAYS AS (if((json_unquote(json_extract(`data`,'$.deliveryId')) like '57%'),json_unquote(json_extract(`data`,'$.deliveryId')),NULL)) STORED,
  PRIMARY KEY (`notification_id`),
  UNIQUE KEY `trigger_event_id` (`trigger_event_id`,`notification_type_id`),
  KEY `user_id` (`user_id`),
  KEY `notified_at` (`notified_at`,`last_attempt_at`,`failed_attempts`),
  KEY `cart_id` (`cart_id`,`user_id`,`notification_type_id`),
  KEY `remote_id` (`remote_id`),
  KEY `notification_type_id` (`notification_type_id`,`notified_at`),
  KEY `delivery_id` (`delivery_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1200024531424 DEFAULT CHARSET=utf8mb4;
```

**Environment**
- Skeema version: skeema version 1.7.0-community, commit d2c91d4c695e5c6d25c37f147f955caefdfdd03b, released 2022-01-24T22:26:51Z
- Database vendor, version, OS/platform: MySQL 5.7.33 on AWS RDS (Linux)

---

Thank you in advance for any help with the issue! :-)

**Comment by evanelias** [comment] 2022-03-02 17:59
Thank you for the report! I can confirm this is a Skeema bug.

The problem is occurring due to the `like` keyword in this generated column expression:
```
`delivery_id` bigint(20) unsigned GENERATED ALWAYS AS (if((json_unquote(json_extract(`data`,'$.deliveryId')) like '57%'),json_unquote(json_extract(`data`,'$.deliveryId')),NULL)) STORED,
```

Skeema has some logic to prevent use of [MySQL's `CREATE TABLE ... LIKE` statement](https://dev.mysql.com/doc/refman/5.7/en/create-table-like.html), since this type of statement is ordering-dependent and works differently than normal `CREATE TABLE`. But unfortunately this detection logic is faulty -- apparently it will incorrectly trip on perfectly-harmless generated columns or check constraints which happen to use `LIKE`.

The core fix to this logic should be simple, but I'll need to give this more thought, as it might make sense to finally add support for `CREATE TABLE ... LIKE` instead anyway. Either way, I'll comment again when I have a better sense of fix ETA. The likely range for the next binary release will be somewhere between 1 week (if next release ends up being a patch release v1.7.1) to at most 8 weeks (if the next release ends up being a feature release v1.8.0), but a fix will be committed here sooner if you build from source.

In the meantime, you may be able to use Skeema with your other tables if you wish, by skipping this table via an ignore-table regex: `skeema init --ignore-table='^notifications$' ...`. This way, `skeema init` will ignore this table, and will also automatically persist the ignore-table regex to a generated .skeema config file so that subsequent commands also ignore the table. Once a new release with a fix is available, you can then remove the ignore-table regex from that file and use `skeema pull` to finally bring the notifications.sql into your schema repo.

Sorry about this bug and thanks again for the report!

**Comment by jakubkulhan** [comment] 2022-03-03 07:54
Aah, I suspected it has something to do with the generated columns, thank you for pointing out which one it is. As a workaround, I've changed the column definition not to use `LIKE` and init works now.

This issue should get fixed, but you don't need to rush it. Thank you for developing Skeema.

**Comment by evanelias** [comment] 2022-03-22 20:50
Quick update on this issue: a fix will be committed to the main branch later today. The next binary release will most likely be v1.7.1 sometime next week, including this fix and a few other minor bug fixes. Thanks again for the issue report!

**Closed** 2022-03-22 23:05 UTC
Labels: bug

**Comment by jakubkulhan** [comment] 2022-03-24 12:13
Thank you for your work!

**Comment by evanelias** [comment] 2022-03-30 16:29
Happy to announce [Skeema v1.7.1](https://github.com/skeema/skeema/releases/tag/v1.7.1) is now available and contains this fix.
