### ISSUE TITLE
Support for check constraints

### ISSUE THREAD

**Issue by derekperkins** [skeema/skeema#86] opened 2019-07-17 12:07 UTC
Now that upstream MySQL supports `CHECK` constraints in addition to MariaDB, is adding support slated for the near future?

**Comment by evanelias** [comment] 2019-07-17 15:54
It's possible in theory, but nothing concrete planned yet. Prioritization will depend on the feature's adoption rate in the MySQL and MariaDB communities.

This could be a good candidate for a 3rd party pull request, or corporate sponsored development if a company needs it soon.

It's worth mentioning that the implementation differences between MySQL and MariaDB add some considerable headaches for automation tools here:
* Check constraints are schema-namespaced in MySQL, meaning a given check name can only appear once per database -- like foreign keys, although that's a separate namespace, meaning that you can have an FK and a CHECK with the same name in the same database or even same table. Meanwhile in MariaDB, CHECK constraints are *table*-namespaced; you can reuse the same name within a database on different tables.
* In MySQL, check constraints are dropped via syntax `ALTER TABLE ... DROP CHECK` whereas MariaDB uses `ALTER TABLE ... DROP CONSTRAINT`
  * This is especially problematic in MariaDB if you have an FK and a CHECK with the same name on the same table. If you want to drop the CHECK but keep the FK, as far as I can tell there's no correct syntax for this. You have to use `DROP CONSTRAINT` which may randomly drop the FK instead of the CHECK 🤦‍♂ 
* As a result of the namespacing difference, in `information_schema.check_constraints`, MariaDB includes a [table_name col](https://mariadb.com/kb/en/library/information-schema-check_constraints-table/), whereas MySQL [does not](https://dev.mysql.com/doc/refman/8.0/en/check-constraints-table.html). This means the schema introspection queries / join conditions will need to differ between the two. There may be other `information_schema` differences as well, it would require more research.
* Apparently MariaDB only added `information_schema.check_constraints` in later point releases of 10.2 and 10.3 within the past year, despite check constraints themselves being added a few years earlier. If the check clauses aren't exposed anywhere in `information_schema` in earlier releases, Skeema would either need to parse them from `SHOW CREATE TABLE`, or just not support them in those earlier releases.
* Since MySQL also only added CHECKs in a point release, the `information_schema` queries here would either need to ignore failures, or Skeema's abstraction around [flavor](https://github.com/skeema/skeema/blob/master/doc/options.md#flavor) needs to be redesigned to account for point releases. (Unfortunately Skeema's flavor system was designed just prior to MySQL's announcement of regularly adding brand new MySQL features in post-GA point releases, which was completely unexpected, since it violates semantic versioning...)

**Comment by derekperkins** [comment] 2019-09-26 21:19
Would it be possible to operate while ignoring check conditions? What I did temporarily to get things working for me was to remove the check in my sql+db, run `skeema diff/push` and then manually add the constraint back. What I was hoping for was a best effort diff, though I realize that may be impossible without a sql parser.

**Comment by evanelias** [comment] 2019-09-27 03:48
Adding a "best-effort" option to diff/push would actually be pretty easy (~20 lines of code) -- it's more a question of whether it's too risky. Really all this option would do is override one of Skeema's core safety checks, where it confirms that the output of `SHOW CREATE TABLE` matches its expectations from its introspection logic, on both sides of the diff. Essentially, this check confirms that Skeema's "understanding" of a table's structure is fully complete and accurate.

Without that safety check, it's theoretically possible that the generated diff could be "wrong" in subtle ways, beyond things that relate to just the unsupported features. This is rare, but it's always possible in edge cases -- for example, [subtle changes may occur in information_schema between minor mysql-server releases](https://github.com/skeema/skeema/issues/78), or [DBaaS vendors may make similarly arbitrary changes between major versions](https://github.com/skeema/skeema/issues/68).

The "best effort" option would inherently also need to disable the separate-but-related safety check controlled by the [verify](https://github.com/skeema/skeema/blob/master/doc/options.md#verify) option, which basically confirms that `(OLD CREATE) + (GENERATED ALTER) --> (NEW CREATE)`. That check is helpful to identify [legitimately disallowed ALTERs for FK-related reasons](https://github.com/skeema/skeema/issues/102), and historically helped catch [one serious edge-case bug](https://github.com/skeema/skeema/issues/36).

So it's an interested idea, but I'd need to think more about this... if implemented, at minimum the option's docs would need a very loud warning :)

**Comment by derekperkins** [comment] 2019-09-27 15:16
Maybe it becomes a `skeema diff` only option, not `skeema push`, requiring some human intervention to actually execute it, and then update with a `skeema pull`.

**Comment by elvenarg** [comment] 2021-01-25 18:49
Hello, just a friendly note to mention that I would also love to see this implemented.

About the point #2 you mention, it is a bit tricky... if you define a CHECK in place (IE not thru constraint 'name-here' CHECK() ) then that CHECK is unnamed and cannot be dropped with drop constraint directly. (Checked @ MariaDB 10.2)
To drop that CHECK, alter ... modify column ... with the same definition except the check needs to be done.

**Comment by evanelias** [comment] 2021-01-25 23:07
I believe both MySQL and MariaDB will automatically generate a name in that case. If so, it should hopefully be exposed through `information_schema` and `SHOW CREATE TABLE`, but I haven't researched.

**Comment by evanelias** [comment] 2021-02-17 16:28
I researched check constraints further. I'm aiming to implement at least partial support soon, but not sure how many of these wacky edge cases will be covered. I'm including my notes here mostly just for my own reference.

@elvenarg you're correct about how MariaDB treats unnamed inline-column CHECKs -- there's no way to manipulate them outside of modifying the column they're on. In `SHOW CREATE TABLE` they show up on the column line, rather than as a separate CONSTRAINT line. In information_schema they're returned with a name equal to the column name, but there's no way to manipulate it using that name, and there's no differentiating data in information_schema to tell these inline CHECKs apart from other CHECKs. MariaDB will even allow you to create a named CHECK on the same table with a name equal to a column name, even if that column also has an inline CHECK!

MySQL handles this better: inline-column CHECKs get handled the same way as regular unnamed checks. They'll get auto-assigned a sequentially-generated name, they can be manipulated directly with that name, and they show up as separate constraint lines in `SHOW CREATE TABLE`. However, MySQL butchers the information_schema data in other ways: the backslash-escaping of special chars is inexplicably performed twice (so the clause is no longer valid SQL). Also since MySQL doesn't have an information_schema.check_constraints.table_name column, it's necessary to *also* query or join information_schema.table_constraints.

MySQL provides the ability to enable/disable individual checks via the ENFORCED / NOT ENFORCED clause, and supports ALTER CHECK clause of an ALTER TABLE to manipulate this field. MySQL exposes this in information_schema.table_constraints but not in information_schema.check_constraints. MariaDB doesn't provide a way to toggle individual checks, but does offer global or per-session `SET check_constraint_checks=0;` which MySQL lacks.

**Comment by evanelias** [comment] 2021-02-23 00:15
Happy to say that support for check constraints has been implemented! It's in the main branch now, and will be included in the upcoming release of Skeema v1.5.0. Check constraint support is also now available immediately in [Skeema Cloud Linter](https://www.skeema.io/cloud/).

I believe I caught all the known edge cases for both MySQL 8 and MariaDB, but if anyone encounters unexpected behavior, please open a new bug report issue.

**Closed by evanelias** 2021-02-23 00:15 UTC
Labels: feature request, help wanted

**Comment by derekperkins** [comment] 2021-02-23 00:23
Woohoo!! That's awesome, it certainly didn't sound simple from that last comment. Thanks for the hard work!
