### ISSUE TITLE
skeema push with multiple Fulltext keys

### ISSUE THREAD

**Issue by sreekan2** [skeema/skeema#150] opened 2020-12-08 17:50 UTC
Using skeema from release v1.4.6 on a sample table:
`CREATE TABLE `duplicate_index` (
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `title` varchar(200) NOT NULL DEFAULT '',
  `data` text,
  KEY `ix_title` (`title`),
  FULLTEXT KEY `ft_title` (`title`),
  FULLTEXT KEY `ft_data` (`data`)
) `

I am trying to create a table with multiple Fulltext keys and I am getting below error
"Error 1795: InnoDB presently supports one FULLTEXT index creation at a time".
looks like skeema got some kind of limitation creating a table with multiple keys.

**Comment by evanelias** [comment] 2020-12-08 17:57
Thank you for the issue report. This appears to be a limitation on the database side. Please let me know what database vendor (MySQL, MariaDB, Percona Server, Aurora, etc) and version are you using and I'll investigate further.

If this error comes directly from running a CREATE TABLE though, it may be difficult to fix directly in Skeema, as there aren't currently any other situations where a new table emits both a CREATE and immediate ALTER at the same time. 

As a work-around you may be able to do that somewhat manually -- initially write the table definition with just 1 fulltext index, run `skeema push`, adjust the CREATE to add the second fulltext index, and then `skeema push` again.

**Comment by sreekan2** [comment] 2020-12-08 18:02
My apologies, I didn't mention earlier, I am using MySQL 8.0.22.
I got no issue running the script directly but only with Skeema. I will try the workaround you suggested and will let you know the outcome.

**Comment by evanelias** [comment] 2020-12-08 23:01
When you first encountered this error from `skeema push`, were you creating a *brand new* table with multiple FULLTEXT indexes? Or were you adding multiple FULLTEXT indexes to an *existing* table?

So far I haven't been able to reproduce this in a *new* table -- I can *create* a table with multiple fulltext indexes just fine, whether manually or through `skeema push`. And the tengo package's integration test suite actually already includes a case with [multiple FULLTEXT indexes](https://github.com/skeema/tengo/blob/v0.9.6/testdata/ft-parser.sql) and that test succeeds correctly.

However I can indeed reproduce this error when *altering* an *existing* table, in any attempt to add multiple fulltext indexes at once, again whether manually or through `skeema push`. That's a bug, but hopefully it should be easy to fix, since there's already other situations in which clauses need to be broken up into multiple ALTERs.

If you're able to reproduce this on a *new* table, if you can please provide a cut-and-paste / screen grab of what's happening, that may help reproduce this. In any case, thank you again for the issue report, as the multi-fulltext-alter situation is definitely a Skeema bug that should be fixed.

**Comment by evanelias** [comment] 2020-12-10 15:39
Hi @sreekan2, just checking back in on the above questions. I have a fix ready for the "altering a table to add multiple FULLTEXT indexes" case, but am waiting to merge to hear more, regarding if *new* tables are affected too / how to repro that if so. Thanks!

**Comment by sreekan2** [comment] 2020-12-10 15:52
Hi @evanelias , Thanks for your response, you were correct, when we creating the table for the first time there are no issues, the issue only happens when we adding FULLTEXT keys after the creation.

**Comment by evanelias** [comment] 2020-12-10 16:07
Awesome, thank you! I'll merge the fix to the main branch momentarily. Might be a few months until the next binary release though.

**Comment by evanelias** [comment] 2020-12-10 16:20
One other quick thing to mention, another workaround is to use [alter-algorithm=copy](https://www.skeema.io/docs/options/#alter-algorithm), e.g. `skeema push --alter-algorithm=copy`. This will run a multiple-FULLTEXT `ALTER TABLE` successfully in the current version of Skeema . The downside is that this form of ALTER runs more slowly, and in some situations may also interfere with concurrent writes to the table. 

For large tables, configuring Skeema to use an [external OSC tool](https://www.skeema.io/docs/faq/#how-do-i-configure-skeema-to-use-online-schema-change-tools) is another workaround for this bug.

**Closed** 2020-12-10 16:28 UTC

**Comment by evanelias** [comment] 2021-01-05 23:49
This fix has been included in [Skeema CLI v1.4.7](https://github.com/skeema/skeema/releases/tag/v1.4.7), released today.
