### ISSUE TITLE
SHOW CREATE TABLE does nor order CONSTRAINTs in MySQL 5.5

### ISSUE THREAD

**Issue by thinQ-skeema** [skeema/skeema#83] opened 2019-07-11 20:43 UTC
In MySQL 5.5 (and earlier versions) the SHOW CREATE TABLE output does not order lines with FOREIGN KEY constraints. For example, the  SHOW CREATE TABLE may provide:
`        CREATE TABLE constraints (`
`          name varchar(30) DEFAULT NULL,`
`          code char(20) CHARACTER SET latin1 COLLATE latin1_bin,`
`          num int(10) unsigned NOT NULL,`
`          KEY idx1 (name) COMMENT 'lol',`
`          KEY idx2 (num),`
`          CONSTRAINT num_fk FOREIGN KEY (num) REFERENCES nums (num), `
`          CONSTRAINT name_fk FOREIGN KEY (name) REFERENCES names (name)`
`        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;`

In contrast, the [instance.go](https://github.com/skeema/tengo/blob/master/instance.go#L932) orders lines with constraints per
`ORDER BY BINARY rc.constraint_name, kcu.ordinal_position`

This leads to `actual != expected` [here](https://github.com/skeema/tengo/blob/master/instance.go#L991) resulting in the table flagged as having UnsupportedDDL, which prevents skeema from generating DDL operations on that table.

**Comment by evanelias** [comment] 2019-07-12 15:32
Great catch, thank you for the excellent bug report! I now have a simple automated reproduction for MySQL 5.5 and Percona Server 5.5. Luckily, newer versions (5.6+) are unaffected. 

Please see https://github.com/skeema/tengo/commit/72ffc93f119c4a01080ea57061727a68ed3b8da0 for the test change (currently in a branch), and https://gist.github.com/evanelias/7516e31e6685df34a73c86d082895de6 for test execution and output. (If trying to run the tests locally, just be aware this requires [Dep](https://github.com/golang/dep), Docker, enough disk space to store 11 mysql/mariadb Docker images locally, and several minutes of execution time.)

Please let me know if you'd like to try a fix PR using a similar approach as [fixIndexOrder()](https://github.com/skeema/tengo/blob/dda2538ad60ecc114a2ed3fabf1c244a7029ed91/instance.go#L1000-L1014)? Also happy to try on my end, up to you. Either way, thanks again!

**Comment by thinQ-skeema** [comment] 2019-07-13 01:11
I like you suggestion and submitted the PR with updated .travis.yml line just for this test.

**Comment by evanelias** [comment] 2019-07-13 03:48
Awesome, thank you! Your PR in [skeema/tengo](https://github.com/skeema/tengo) is now merged.

The final step will be to update the frozen version of [skeema/tengo](https://github.com/skeema/tengo) used here in [skeema/skeema](https://github.com/skeema/skeema). I can do this on my end, or if you'd like to open a PR for it let me know. The process requires a slightly-old* version of the [dep](https://github.com/golang/dep) tool, [v0.4.1](https://github.com/golang/dep/releases/tag/v0.4.1), and just looks like this:

```
cd $GOPATH/src/github.com/skeema/skeema # or wherever you have a clone of skeema/skeema
dep ensure -update github.com/skeema/tengo
git commit -a
```
That should automatically bring in some changes to vendor/github.com/skeema/tengo/, and also updates Gopkg.lock.


<sub>\* Dep v0.5.0 breaks backwards-compatibility and I never got around to upgrading. I'm likely going to switch to using Golang v1.11's Modules functionality instead in a few weeks, and move away from Dep entirely.</sub>

**Comment by thinQ-skeema** [comment] 2019-07-13 22:23
Locally I got one test failing:    
--- FAIL: TestIntegration/SkeemaIntegrationSuite.TestFlavorConfig:mysql:5.7 (1.18s)
        skeema_cmd_test.go:1041: Expected init to skip flavor, but it was found

As I was unable to configure Travis-CI for my repo clone, I submit the PR anyway.

**Comment by thinQ-skeema** [comment] 2019-07-13 23:04
My PR build failed at 
=== RUN   TestIntegration/SkeemaIntegrationSuite.TestAddEnvHandler:mysql:5.6
/home/travis/gopath/src/github.com/skeema/skeema/testdata/.scratch/mydb: Error 1193: Unknown system variable 'information_schema_stats_expiry')

**Closed** 2019-07-15 02:35 UTC
Labels: bug
