### ISSUE TITLE
Foreign keys with underscore prefixed names may be erroneously flagged as unsupported by skeema

### ISSUE THREAD

**Issue by mv-steven** [skeema/skeema#32] opened 2018-07-12 22:03 UTC
I'm using skeema with pt-online-schema-change.  I have a table called 'pets' that has a foreign key referencing an 'owners' table.  This constraint is called 'owner_fk'.  I changed pets.sql to 1) add a new column (pet_type_id), and 2) setup the new pet_type_id column as a foreign key reference to a new 'pet_type' table.  This means that skeema will run pt-online-schema-change twice to add the column and add the new constraint.  We know that pt-online-schema-change will prefix existing constraints with an underscore.

The first time I run pt-osc to add the column, 'owner_fk' gets renamed to '_owner_fk', as we would expect.  I run 'skeema diff' and everything is fine.  The second time I run pt-osc, the new foreign key to 'pet_type' gets created, and '_owner_fk' is now renamed to '__owner_fk'.  Now when I run skeema diff, I get this:

```
$ skeema diff --debug
2018-07-12 16:40:57 [INFO]  Generating diff of localhost:/var/run/mysqld/mysqld.sock mydb vs /home/steven/skeema/mydb/*.sql
2018-07-12 16:40:57 [WARN]  Skipping table pets: unable to generate ALTER TABLE due to use of unsupported features. Use --debug for more information.
2018-07-12 16:40:57 [DEBUG] --- Expected
2018-07-12 16:40:57 [DEBUG] +++ MySQL-actual
2018-07-12 16:40:57 [DEBUG] @@ -8,2 +8,2 @@
2018-07-12 16:40:57 [DEBUG] -  CONSTRAINT `pet_type_fk` FOREIGN KEY (`pet_type`) REFERENCES `pet_type` (`id`),
2018-07-12 16:40:57 [DEBUG] -  CONSTRAINT `__owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`)
2018-07-12 16:40:57 [DEBUG] +  CONSTRAINT `__owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`),
2018-07-12 16:40:57 [DEBUG] +  CONSTRAINT `pet_type_fk` FOREIGN KEY (`pet_type`) REFERENCES `pet_type` (`id`)
2018-07-12 16:40:57 [INFO]  localhost:/var/run/mysqld/mysqld.sock mydb: diff complete

2018-07-12 16:40:57 [WARN]  Skipped 1 operation due to unsupported feature
2018-07-12 16:40:57 [DEBUG] Exit code 1
```
Here's my pets.sql file:
```
$ cat pets.sql
CREATE TABLE `pets` (
  `name` varchar(30) NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  pet_type bigint(20) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`name`,`owner_id`),
  KEY `owner_fk` (`owner_id`),
  KEY `pet_type_fk` (`pet_type`),
  CONSTRAINT `owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`),
  CONSTRAINT `pet_type_fk` FOREIGN KEY (`pet_type`) REFERENCES `pet_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```
Here is my table before any modification by pt-osc:
```
CREATE TABLE `pets` (
  `name` varchar(30) NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`name`,`owner_id`),
  KEY `owner_fk` (`owner_id`),
  CONSTRAINT `owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
Here's the table after the first modification:
```
CREATE TABLE `pets` (
  `name` varchar(30) NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  `pet_type` bigint(20) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`name`,`owner_id`),
  KEY `owner_fk` (`owner_id`),
  KEY `pet_type_fk` (`pet_type`),
  CONSTRAINT `_owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
'owner_fk' is now '_owner_fk.  At this point, 'skeema diff' doesn't report anything unusual; it just reports that it need to run pt-osc again to add the new fk constraint to get up to par with pets.sql.  Here's the final table structure after running pt-osc the final time:
```
CREATE TABLE `pets` (
  `name` varchar(30) NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  `pet_type` bigint(20) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`name`,`owner_id`),
  KEY `owner_fk` (`owner_id`),
  KEY `pet_type_fk` (`pet_type`),
  CONSTRAINT `__owner_fk` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`),
  CONSTRAINT `pet_type_fk` FOREIGN KEY (`pet_type`) REFERENCES `pet_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
'_owner_fk' was renamed to '__owner_fk'.  At this point when I run 'skeema diff' I get the messages I listed above.

I included a zip file with the database structure and the files skeema generated.  Just run 'mysql < mydb2.sql' to create the structure I'm using, run 'skeema push' then 'skeema diff' and you'll see what I'm talking about.

[mydb.zip](https://github.com/skeema/skeema/files/2190447/mydb.zip)

**Comment by evanelias** [comment] 2018-07-13 05:22
Thank you for the bug report! I've reproduced it as described, and found the root cause is pretty subtle -- it relates to how underscores are sorted in common MySQL collations. The simplest reproduction is that if a table contains some foreign key names with underscore prefixes, Skeema will sort these differently than `SHOW CREATE TABLE`, causing Skeema to think the table is using unsupported features.

In brief, `SHOW CREATE TABLE` always displays foreign keys in a sorted order by name, regardless of what order they were added in. Skeema attempts to reproduce this order by also sorting foreign keys by name; see https://github.com/skeema/tengo/blob/98ba7332f14be79827454c2deeaad6111d7564d1/instance.go#L771. However, this query is using a collation by default, which sorts underscores *after* letters. But meanwhile it seems `SHOW CREATE TABLE`'s sort is comparing binary character values, meaning underscores come after uppercase letters but before lowercase letters.

Fortunately, this is easy to fix (changing `rc.constraint_name` to `BINARY rc.constraint_name` in that `ORDER BY` clause), as well as capture in a test case. I'll make a new patch release of Skeema within the next day, and will close this out then. Thanks again for the thorough issue report!

**Comment by evanelias** [comment] 2018-07-13 19:19
Fixed in https://github.com/skeema/skeema/commit/1a1631a668; released as [v1.0.2](https://github.com/skeema/skeema/releases/tag/v1.0.2). Please let me know if you experience any other problems with the interaction between Skeema, pt-osc, and foreign keys -- thanks again!

**Closed by evanelias** 2018-07-13 19:19 UTC
Labels: bug

**Comment by mv-steven** [comment] 2018-07-13 19:58
Nice! I'll check it out as soon as I can.  Thanks!

**Comment by mv-steven** [comment] 2018-07-16 19:16
Just following up - I re-ran the scenario I sent you and it looks great.  Thanks again!
