### ISSUE TITLE
Intermittent Connection Issues and Runtime Error in 'skeema push' Command on Red Hat 7 with MariaDB 10.3

### ISSUE THREAD

**Issue by srirams1225** [skeema/skeema#229] opened 2024-07-30 14:50 UTC
**Describe the bug**

Occasionally, the 'skeema push' command fails with connection issues and a runtime error when running it in a loop on a Red Hat 7 webserver that connects to a MariaDB 10.3 database server. The issue seems to occur when pushing schema changes to 300 databases simultaneously.
**Environment**
- Skeema version and OS: 
- Database vendor, version, OS/platform: 
- Any other environmental notes, special Skeema configuration, or Skeema warnings logged about your database server version:
- Skeema version and OS: Skeema v1.12 running on Red Hat 7 (noticed same issue on previous versions of skeema as well, but logs are better in 1.12)
- Database vendor, version, OS/platform: MariaDB 10.3 running on Red Hat 7 in Azure
- skeema host and database are in same network and there are no conection issues between then in that azure subnet.

**To Reproduce**

Run the 'skeema push' command from the webserver in a loop for 300 databases simultaneously.

Observe intermittent connection issues and a runtime error
**Expected behavior**

we should not notice any occational skeema connection failures for some set of databases for a given list, when all the databases are with same connection details and network.

**Additional context**

logs:
```
[mysql] 2024/07/29 21:50:02 connection.go:49: read tcp ipaddress:port->ipaddress:port: i/o timeout
2024-07-29 21:50:28 [ERROR] Uncaught panic in github.com/skeema/plus/internal/workspace.ExecLogicalSchema at github.com/skeema/plus/internal/workspace/workspace.go:535: runtime error: invalid memory address or nil pointer dereference
2024-07-29 21:50:28 [ERROR] This situation indicates a bug in Skeema. Use --debug to view the full stack trace.
2024-07-29 21:50:28 [ERROR] Please e-mail bugs@skeema.io with any available background information.
```
script we run in loop is 

```
for  i in $(cat database-list) ; do ;
export SKEEMA_CONFIG_DIR='/var/www/mysql_schema' && \
export SKEEMA_SECRET_KEY={{ skeema_secret }} && \
export SCHEMA_DIR='data/schema' && \
export LOCAL_DB_HOST=db_host && \
export LOCAL_DB_PORT=3306 && \
export LOCAL_DB_USER=dbuser && \
export LOCAL_DB_PASS=password && \
export DATABASE="$i" && \
../../.cicd/skeema push localhost --allow-unsafe --skip-lint >> /var/log/skeema/"$i".log 2>&1 ;
done
```

**Comment by evanelias** [comment] 2024-07-30 21:39
Thank you for the report! There are actually 2 separate things happening here:

1) During the [workspace](https://www.skeema.io/docs/features/workspaces/) step of `skeema push`, one of Skeema's queries is timing out. It's not a connectivity problem specifically, nor a Skeema bug. It just means the database server isn't responding in a reasonable amount of time (20 seconds by default).

2) The error logging/handling for this specific situation (a query timing out or failing, during the workspace step) has a bug in Skeema Premium v1.12.0, which is what is causing the "uncaught panic" logging. Upon investigating, I found this happens when a workspace query fails, *and* the directory contained at least one CREATE EVENT statement. This is definitely a Skeema bug, which will be fixed in the next release. However the fix for this just restores the logging to the correct pre-v1.12.0 behavior. So this is a fairly minor / non-urgent bug, as the panic only comes up when some *other* error already happened in this specific place, which is normally very infrequent.

So to solve the real root cause here, you need to prevent the query time-out. The proper fix for that is to get rid of the bash loop -- it is problematic to invoke `skeema push` hundreds of times in a loop for the same subdirectory and same db server. That's going to hammer the server with expensive queries, due to how workspaces function. The server probably can't keep up with all that i/o.

Skeema's sharding feature solves this problem, it will just run the workspace step a single time per subdirectory. It will also perform much faster overall. In your .skeema file you probably want either ```schema=`cat database-list` ``` or ```schema=$SOME_ENV_VAR_WITH_ALL_THE_DBS``` or maybe ```schema=*``` but it totally depends on your shard layout.

Alternatively, as a temporary work-around, you could try increasing Skeema's timeouts in connect-options, or tuning Skeema's various workspace options. But these aren't good long-term solutions since they don't address the root cause of all that extra workspace i/o from the loop.

Also consider upgrading your database server version, as [MariaDB 10.3 hit its end-of-life in May 2023](https://mariadb.com/kb/en/changes-improvements-in-mariadb-10-3/). So it is always possible that there are unsolved performance issues in MariaDB 10.3 which could contribute to the problem here.

Closing this out, as we've internally committed a fix for the logging bug now, which will be included in v1.12.1 whenever that is released (schedule TBD, possibly a few months). Thanks again for the report.

**Closed by evanelias** 2024-07-30 21:39 UTC
Labels: bug

**Comment by srirams1225** [comment] 2024-07-31 01:21
Thank you for quick response.

**Comment by evanelias** [comment] 2024-12-02 22:21
Today's release of [Skeema v1.12.1](https://github.com/skeema/skeema/releases/tag/v1.12.1) fixes the panic message, so the original workspace query error (e.g. query timeout) is now displayed properly, as it was prior to v1.12.0. Thanks again for the issue report!
