### ISSUE TITLE
Skeema pull on a table with system versioning

### ISSUE THREAD

**Issue by Jengym1** [skeema/skeema#206] opened 2023-03-10 17:32 UTC
**Describe the bug**
When I run skeema pull, a table with system versioning is not being generated (the .sql file is deleted if it is already there)

**Environment**
- Skeema version: *[v1.9.0]*
- Database vendor, version, OS/platform: *[MariaDB 10.6.10 running on AWS]*

**To Reproduce**
Maria db with at least one table that has system versioning on;  run skeema pull;  see if that table is in the .sql files created

**Expected behavior**
That table should be in the list, and the sql for the create should include the system versioning information

**Additional context**
I did find this in your documentation (copied below), but it doesnt' really describe the behavior I am seeing.  Do I need to add an option with the skeema pull?  Can you tell me why it may be skipping this table altogether?

From your website:
Unsupported for ALTER TABLE
Skeema can CREATE or DROP tables using these features, but cannot ALTER them. The output of skeema diff and skeema push will note that it cannot generate or run ALTER TABLE for tables using these features, so the affected table(s) will be skipped, but the rest of the operation will proceed as normal.

spatial indexes
sub-partitioning (two levels of partitioning in the same table)
general tablespaces (explicit TABLESPACE clauses other than innodb_system or innodb_file_per_table)
******MariaDB’s system versioned tables / bitemporal tables / application time periods*****
some features of non-InnoDB storage engines
You can still ALTER these tables externally from Skeema (e.g., direct invocation of ALTER TABLE or pt-online-schema-change). *****Afterwards, you can update your schema repo using skeema pull, which will work properly even on these tables.****

(this is what I did, updated it outside of Skeema; but when I did the pull the file disappeared altogether.  I tried adding a new table with system versioning, and the table did not get a .sql file on the skeema pull)

THANKS!

**Comment by evanelias** [comment] 2023-03-10 20:56
Thank you for the report. Please see #187 for the root cause: despite using `CREATE TABLE` syntax, system-versioned tables have a nonstandard value in `information_schema.tables.table_type`, so Skeema effectively does not see them at all when it queries `information_schema.tables` to see which tables exist.

You're correct that the Skeema docs are mistaken on this point, sorry about that. They've been updated now to reflect the current situation: system-versioned and bitemporal tables are ignored entirely, whereas tables using application-time periods aren't supported for diff/push but do show up in init/pull/format.

Closing since the feature request for system-versioned tables is tracked in #187. Unless the level of demand for system-versioned tables increases (especially among Skeema Premium users), the most likely path forward would be either a pull request (if a third party company can implement the support end-to-end) or a sponsored development contract (if a company is willing to pay for the necessary dev time).

**Closed by evanelias** 2023-03-10 20:56 UTC
Labels: bug

**Comment by evanelias** [comment] 2023-03-10 21:02
btw if you want to create the .sql file manually while also preventing `skeema pull` from deleting it, [ignore-table](https://www.skeema.io/docs/options/#ignore-table) should hopefully work properly for that use-case, but I haven't tested with this particular scenario of system-versioned tables.

**Comment by evanelias** [comment] 2023-12-04 23:21
Minor quality-of-life improvements for system-versioned tables in today's release of [Skeema v1.11.1](https://github.com/skeema/skeema/releases/tag/v1.11.1): 

Upon encountering a `CREATE TABLE ... WITH SYSTEM VERSIONING` statement among the *.sql files, Skeema will now log a warning, and will otherwise ignore the table (same behavior as if it had matched the ignore-table option). This means `skeema pull` will no longer delete the CREATE statement from the file.

Otherwise though, system-versioned tables (including bitemporal tables) are still completely unsupported, and won't even be introspected or dumped from the server. No ETA for a fix yet, but this remains a good potential area for a community PR.
