### ISSUE TITLE
Errors when using on Amazon RDS build of MariaDB 10.3

### ISSUE THREAD

**Issue by jmillstein** [skeema/skeema#68] opened 2019-04-04 21:51 UTC
We had skeema running nicely yesterday on Mariadb10.2 , we then updated to 10.3 and are getting errors on all table statements.  We have messed around with user permissions including using the root user that has all grants on the db and the skeema temp db.  The error message we are getting is the following.

2019-04-04 21:48:02 [WARN]  Skipping table `myTable`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2019-04-04 21:48:02 [DEBUG] --- Expected CREATE
2019-04-04 21:48:02 [DEBUG] +++ MySQL-actual SHOW CREATE

it's really confusing because there is not SHOW CREATE in our sql files.... Any help would be awesome.

**Comment by jmillstein** [comment] 2019-04-04 22:01
more info.  we just rolled back to mariadb 10.2 and it works.  I looked at the release notes and couldn't find anything that looked like it was an issue.

**Comment by evanelias** [comment] 2019-04-04 22:04
Weird, that's definitely unexpected -- MariaDB 10.3 is fully supported and included in the integration testing suite. 

What exact version of MariaDB 10.3 are you using? Are there any lines in the debug output after the ones you included above? The following lines should indicate what part of the table Skeema is having trouble with.

For context, Skeema runs `SHOW CREATE TABLE` automatically as a safety-check. This warning means that `SHOW CREATE TABLE` is returning something different than what Skeema expects, based on its introspection of the table's attributes from `information_schema`.

**Comment by jmillstein** [comment] 2019-04-04 22:15
we are using ... 10.3.8-MariaDB-log .

Yes , there are and I just noticed that there is a difference in quotes in the diff

2019-04-04 21:48:02 [DEBUG] @@ -3,5 +3,5 @@
2019-04-04 21:48:02 [DEBUG] -  `ClassName` enum('MVSetting') DEFAULT '''MVSetting''',
2019-04-04 21:48:02 [DEBUG] -  `Created` datetime DEFAULT 'NULL',
2019-04-04 21:48:02 [DEBUG] -  `LastEdited` datetime DEFAULT 'NULL',
2019-04-04 21:48:02 [DEBUG] -  `Text` varchar(255) DEFAULT 'NULL',
2019-04-04 21:48:02 [DEBUG] -  `IsDeleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
2019-04-04 21:48:02 [DEBUG] +  `ClassName` enum('MVRepSetting') DEFAULT 'MVRepSetting',
2019-04-04 21:48:02 [DEBUG] +  `Created` datetime DEFAULT NULL,
2019-04-04 21:48:02 [DEBUG] +  `LastEdited` datetime DEFAULT NULL,
2019-04-04 21:48:02 [DEBUG] +  `Text` varchar(255) DEFAULT NULL,
2019-04-04 21:48:02 [DEBUG] +  `IsDeleted` tinyint(1) unsigned NOT NULL DEFAULT 0,

**Comment by evanelias** [comment] 2019-04-04 22:35
Awesome, thanks, that's helpful -- looks like Skeema is interpreting column default values incorrectly in your environment. I haven't been able to reproduce this yet on a fresh copy of 10.3.8, but I'll keep digging and will comment again once I've tried a few more things (hopefully by eod tomorrow).

It might be a situation which is specific to upgrading. Out of curiosity, do you recall which version of MariaDB you were using when you first created these tables? (even just major.minor is helpful for this one, e.g. 10.1 vs 10.2). Thanks again!

**Comment by jmillstein** [comment] 2019-04-04 22:41
Yes, it was 10.2. Thank you for the help!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by evanelias** [comment] 2019-04-05 06:07
I haven't been able to reproduce the problem yet, but I have a hunch that Skeema is failing to parse the version or vendor properly on your copy of MariaDB 10.3. 

Can you please run this query on a copy of 10.2 and 10.3 in your environment?

```sql
SELECT @@global.version_comment, @@global.version;
```

Also out of curiosity, did you use the same distribution source (e.g. rpm repository, mariadb.com download, docker image, compile from source, etc) for 10.3 as for 10.2?

If the problem is where I think, the good news is that the fix should be straightforward -- if so, I can release a new build of Skeema with the fix by early next week.

**Comment by jmillstein** [comment] 2019-04-05 14:23
Yep, for the 10.3 environment . --> Source distribution	10.3.8-MariaDB-log
for the 10.2 environment --> MariaDB Server	10.2.15-MariaDB-log

These are both setup using aws rds.  

Thanks again for all the help

**Comment by evanelias** [comment] 2019-04-05 18:18
Perfect, that explains it! Judging by the version_comment, it seems Amazon is using a different build process behind the scenes for their MariaDB 10.3 vs what they used in 10.2. 

Currently, Skeema only looks at `@@global.version_comment` to parse the vendor, as this value normally mentions "mariadb" for all official MariaDB builds. And if that string doesn't contain "mariadb", Skeema doesn't enable MariaDB-specific changes in its behavior. Since MariaDB represents some values in `information_schema` differently than MySQL or Percona Server, it causes the breakage that you're seeing.

I'll aim to release a fix early next week, which makes all of this handling more robust:
* If the vendor cannot be parsed from `@@global.version_comment`, also search `@@global.version` for vendor
* If the vendor still cannot be parsed, mention this clearly in debug logging if `--debug` is used
* Improve Skeema's `flavor` option and make its behavior more consistent:
  * If an instance's vendor or version cannot be parsed, go with `flavor` as a fallback, for *all* behaviors. (Currently, `flavor` only impacts *some* behaviors... so even if you manually put `flavor=mariadb:10.3` in a .skeema file, it still won't solve the bug you're seeing yet.)
  * If an instance's vendor and version are parsed successfully, always use that instead of `flavor`. (Currently, `flavor` is used if supplied, which can be "wrong" if you upgrade mysql/mariadb without then running `skeema pull` or otherwise updating the `flavor` in .skeema files)
  * If `flavor` differs from the instance's real value, log a warning.

Huge thank you again for reporting this! It's likely that Skeema hasn't ever worked properly on Amazon RDS's build of MariaDB 10.3, so this is very good to know and fix 👍

**Comment by jmillstein** [comment] 2019-04-05 19:34
Thank you sir!

**Comment by jmillstein** [comment] 2019-04-08 13:38
Hello.. I was just checking out this... https://github.com/skeema/tengo/commit/2c6c9259ddfaa45bf262bc565fa9f1a800f8029e

looks like you made at least some of the changes for this bug fix?   Are these changes complete or is there more coming?

**Comment by evanelias** [comment] 2019-04-08 15:14
Not complete quite yet, work is still in-progress over the next day or two. Once the fixes are complete in master branch of skeema/skeema, I'll close this issue, and then will comment again once new binaries are released.

**Comment by jmillstein** [comment] 2019-04-08 16:13
ok, thank you :)

**Closed** 2019-04-09 21:11 UTC
Labels: bug

**Comment by evanelias** [comment] 2019-04-09 21:41
I've just released [Skeema v1.2.2](https://github.com/skeema/skeema/releases/tag/v1.2.2) which should fix this issue. Thanks again for reporting this! Please let me know if you encounter any other bugs or weirdness when using Skeema on RDS's build of MariaDB 10.3.

**Comment by jmillstein** [comment] 2019-04-10 14:04
Thank you Evan.  Thanks a ton!
