### ISSUE TITLE
Ability to seed the database tables

### ISSUE THREAD

**Issue by mnpenner** [skeema/skeema#22] opened 2018-04-18 17:38 UTC
From [these slides](https://www.percona.com/live/17/sites/default/files/slides/SkeemaPerconaLive2017.pdf), one of the use-cases is:

> Also support patterns such as “every engineer has their own dev DB on localhost”

Which is also a goal for us. However, it's quite difficult to work with an empty database!

Could Skeema be used to "seed" the database with some base set of data so that it doesn't start empty? Or do you think this should be delegated to another tool?

What about for the scenario where a developer adds a new feature, and creates a table for it. When it's deployed into production, it shouldn't start empty there either. For example, a list of options used in a drop-down.

**Comment by evanelias** [comment] 2018-04-18 21:05
My original intention was to leave this to other tools. But a number of folks have asked about this now, so I'm starting to reconsider :)

The exact mechanics will require some more thought, in terms of how best to represent the seed data, and how it is applied:
* Should the seed data be represented as arbitrary SQL statements, or should it be formatted in a particular way to limit it to controlled INSERTs?
  * Arbitrary SQL is very flexible and dynamic, in terms of supporting function calls, computed values, etc
  * However, arbitrary SQL can be a security concern, especially in terms of running things against production DBs. (For contrast, currently Skeema validates that the *.sql files begin with a CREATE TABLE statement, and anything after that statement is ignored by virtue of intentionally disabling multi-statement support.)
* If supporting any arbitrary SQL, would this just go inside the existing *.sql files for each table? Or separate files per table? Or one big seed data file for each schema, i.e. one seed file per schema directory?
* Would the seed data for a table only be inserted only if that table is currently empty? Or is more thorough data diff logic needed?

I've also been thinking about supporting grant/user management in Skeema, which overlaps with some of these questions and can likely re-use some of the same code.

In any case, I'm very open to community feedback, proposals, and/or PRs. Also happy to implement on my end, but the prioritization is still a bit TBD. I'm currently knee-deep in building out a framework for [proper integration testing](https://github.com/skeema/tengo/compare/integration-testing), which will take a few more weeks, but should pay dividends in greatly accelerating future development and ease of community contributions.

**Comment by mnpenner** [comment] 2018-04-18 22:15
> Would the seed data for a table only be inserted only if that table is currently empty? Or is more thorough data diff logic needed?

I've been thinking about this too, and came up with a few different modes of operation:

- Only insert data if the table is empty
- Always insert the data, but with what I call the [on duplicate key do nothing](http://stackoverflow.com/a/4596409/65387) hack (requires unique keys)
- On duplicate key update -- I suppose this option is needed for completeness, but I'm not sure when you'd want to use it. In any case, it could update the table cells to match your seed data when it hits a unique key constraint (and maintain any unspecified columns)
- Insert where not exists -- each insert would have an accompanying WHERE clause to determine if it should be inserted or not
    - Where not exists batch -- instead of a per-record search, run one query to determine if the entire dataset should be inserted or not

I think the "if empty" would be the most common and fastest, but we've had many occasions when we've wanted to add records to an existing table. e.g. we have an "options" table that we pre-populate with data but then can be updated at 'run-time'.

The first three can be implemented even if your seed data is in JSON. The "WHERE" clauses are trickier. Computed data is trickier yet -- I haven't thought of a solution for that.

**Comment by mv-steven** [comment] 2018-07-10 19:42
I like the idea of including INSERT statements in the *.sql files and performing an insert if the table is empty.  This is helpful if we alter an existing table to have a foreign key relationship to a new table that's being created in the same session.  We can put a default record for an ID 0 in the parent table, and then default child records to all have that ID of 0.  Maybe if we need to do something more complex we could have a separate file for the data, or maybe be able to call an external application to generate the records if we have calculated fields or whatever.  I suppose this is a potential security concern as well, just throwing ideas out there.  If I can find some free time I'd like to take a crack at it.

**Comment by evanelias** [comment] 2018-07-10 22:44
Thanks, very open to community suggestions on this one! Hoping to gather as much input as possible, especially around different use-cases and workflows. Ideally let's all converge on a proposal for how the feature should function.

So far, I'm leaning in this direction:
* Seed data goes in a separate file -- one file per table that has seed data. This allows for some simple security safeguards on file contents, without needing a full SQL parser. For example, we could force a seed file to only ever contain a single SQL INSERT statement, affecting a table name matching the filename.
* Seed data files go in a subdirectory of the schema directory. This will help keep things organized, especially if more object types (views, users/grants, triggers, stored procedures) are supported by Skeema in the future -- each type could get its own subdir.
* Initially, just support running the seed INSERT only if a table is empty. Maybe later support alternative modes like full data diff.
* `skeema pull` would need new options for populating seed data files, or perhaps create a new command for that.

These are soft opinions though -- happy to be convinced otherwise if this isn't compatible with common use-cases.

**Comment by feihtthief** [comment] 2019-01-31 19:57
Idea/Question/2-Cents:

I can imagine a few situations where you want to have certain data pre-populated in a very specific manner in a make-it-so type of manner:
```
INSERT INTO `unique_stuff`
 (`id`, `thing` ,`count`) VALUES
 (  1 , 'one'   ,     4 )
,(  2 , 'two'   ,     3 )
,(  3 , 'three' ,     2 )
,(  4 , 'four'  ,     1 )
ON DUPLICATE KEY UPDATE 
 `id`    = VALUES( `id`    )
,`thing` = VALUES( `thing` )
,`count` = VALUES( `count` )
;
```
I would have no idea how to ensure that any extra rows get deleted that are not in the set, unless it becomes part of the work-flow to add delete statement for such cases, which could get messy real quickly?
Temp tables could be used to then do "delete from real-table where not in temp table", but that's equally messy to identify the "right" key to use.

I don't think Skeema can cater to all possible scenarios, but it could go a long way towards facilitating seeding/bootstrapping by providing a mechanism to run in scripts as part of it's push/pull process.
For example a framework to facilitate proper ordering of the execution of sql files by having a seed-set file that dictates the order in which the individual seed files need to get executed.

Being able a specify which seed-sets get included on a per-environment level would probably go a long way towards piece of mind as opt-in requires someone to make the conscious decision to add the seed-set to the environment.

**Comment by evanelias** [comment] 2019-02-01 23:49
Thanks @feihtthief, good suggestions! My own thinking around seed data has been moving in a similar direction lately. There are still some open questions, but I think this combination of features could theoretically handle most use-cases:

* New options to specify arbitrary hook scripts to run before or after push or pull. Skeema would be able to pass variables to the script to give it more context, just like the other preexisting [options that enable shell-outs](https://github.com/skeema/skeema/blob/master/doc/config.md#options-with-variable-interpolation).

  Open questions: For users with multiple hosts and/or multiple schemas, do these hooks run once per schema? Once per host? Once per `skeema` invocation? Only run if there are actually changes to push/pull, or always run? etc... some of these could be configurable, but if all permutations need to be supported, that's pretty complex.

* New options to specify which .sql files map to a given schema. The basic idea is to provide more flexibility around what files are used, in what order, and how the subdirs are laid out.

  The default would still match the current behavior (apply `*.sql` in alphabetical order) but would provide the ability to include/exclude arbitrary files or fileglobs, in this dir or in any other dir. This would allow conditionally including/excluding certain files in an environment. Also permits keeping common object definitions in a single shared dir elsewhere in the repo, without requiring hacky symlinks.

* Direct support for representing seed data as write queries in *.sql files, e.g. `INSERT`, `INSERT IGNORE`, `INSERT ... ON DUPLICATE KEY UPDATE`, `LOAD DATA INFILE`, `UPDATE`, `MERGE`, `DELETE`. Basically what you described in the first part of your reply. Combined with the previous bullet, this would be a flexible way to control seed data in a pure-SQL fashion, while still giving the ability to customize per environment.

  I'm still undecided on this one though. There's a conceptual mismatch here: previously Skeema uses *.sql files just to contain `CREATE` statements, which are declarative. But write queries are more imperative. They would need to be run on every `skeema push`, and it would be the user's responsibility to ensure they're only mapped in for the correct environments, and ensuring the queries are doing the correct conflict resolution for adjusting existing rows when needed. Still, maybe less work for the user vs having to develop custom scripts for the hooks in the first bullet.

All of this is still totally theoretical at this stage, no solid implementation plans/timeline yet.

**Comment by harveyramer** [comment] 2019-03-28 15:32
This will be very helpful when it lands.

**Comment by evanelias** [comment] 2019-03-28 19:43
Thanks @harveyramer, I agree this would be a useful feature. For the sake of transparency around user expectations though, I should clarify that this functionality is not yet under development, and plans are not yet concrete regarding if/when this may happen.

Use-cases around seed data seem to vary quite a bit between companies, and a fully generic solution could be quite complex, requiring substantial development time. The two possible paths at this point are:

a) Delegate seed data management to third-party tools and custom scripts, by adding more configurable hooks to `skeema push`. This is relatively simple to implement, but there are still a number of open questions (see first bullet in my previous reply)... I'd need more feedback before implementing this.

or

b) Directly support seed data management in Skeema. Due to the implementation complexity, a fully generic solution for seed data management would probably require corporate sponsorship in the low to mid 5 figure range, depending on scope.

**Comment by harveyramer** [comment] 2019-03-29 19:22
Yes, I need to be able to add seed data to tables if it is missing, but not overwrite it if it exists. For example, when I add a set of tables that includes a table with a number of possible statuses, those need to be added. When I add a new status and test in DEV, I want to add that status to seed data and have it applied as part of the deployment. 

Skeema has proven incredibly good and trustworthy for schema updates. What tools do you know of to manage such incremental data updates in addition to seeding empty tables?

**Comment by evanelias** [comment] 2019-03-29 21:32
Makes sense, thanks!

On my end I've mostly just seen custom scripts of varying complexity. But I must admit I don't have a ton of experience with seed data management in general, which is one reason I'm hoping to collect a bunch of use-case descriptions in this issue ;)

In terms of open source tools, Percona Toolkit's [pt-table-sync](https://www.percona.com/doc/percona-toolkit/LATEST/pt-table-sync.html) has some related functionality, although overall that tool is geared more towards fixing replication inconsistencies. Back in 2007 its author also wrote a good [blog post](https://www.xaprb.com/blog/2007/03/05/an-algorithm-to-find-and-resolve-data-differences-between-mysql-tables/) detailing the algorithms involved. General-purpose diff'ing of row data is actually pretty difficult to do efficiently at scale. There are simpler solutions (i.e. row-by-row comparison, walking the primary key) but they would perform very badly with a larger set of seed data.

**Comment by zylo47** [comment] 2020-12-02 16:54
@evanelias it looks like issue #128 is basically a duplicate of this one.  So I'm going to add a bit more detail here as to my use-cases.

I've used both SQL Server Data Tools (SSDT) and Liquibase.  SQL Server data tools is kind of a "best of both worlds" tool when it comes to database code deployment automation because it allows you to create a declarative model of the database similar to how Skeema does for MySQL but it also gives you hooks for pre-deployment and post-deployment scripts.  These hooks are literally sqlcmd files that get executed each time the project runs.  You can call out to other files from the root level file, executing them in sequence.  But these calls are not tracked and it runs them every time.

Liquibase, on the other hand, is a changeset (migration) based tool that strings together a bunch of SQL files in the order that you call them.  These files can contain anything (DDL, DML, single statement, multiple statements...).  The one important thing it does do for you is track what has been already executed and gives you the option of marking files re-runnable.  This tracking is done via a table that is added to the database.

What I ended up doing for SQL Server Data Tools is writing a template that logs every execution to a database change log table and tracking whether the execution was successful or not.  I have a helper procedure that checks the table and gets called at the end of the pre-deployment and post-deployment script.  If that procedure detects an error value it raises and error so the pipeline can detect that and halt.  Later when I started using Liquibase, I found out this is almost exactly what Liquibase is doing.

So, I think for Skeema, an ideal solution would be this: enable a hook for both a pre-deployment script process and a post-deployment script process.  Allow it to either be a third party tool (if you wanted to hook in something like Liquibase or pt-table-sync) or a MySQL script.  

To answer some of your points above:

> New options to specify arbitrary hook scripts to run before or after push or pull.

Yes, either arbitrary hooks to third party tool execution or a script file.  Support for both would be ideal.

> do these hooks run once per schema? Once per host?

It should run once per skeema invocation.  (whatever is "project" scoped).

> New options to specify which .sql files map to a given schema. The basic idea is to provide more flexibility around what files are used, in what order, and how the subdirs are laid out.

The pre/post deployment process should run against a single database (in MySQL terminology a single schema).  You would need a database/schema directory scoped entry point.  Perhaps in a sub-directory of each schema.

> The default would still match the current behavior (apply *.sql in alphabetical order)...

If calling a MySQL script entry-point, in my experience, it's best to call them in the order they exist in the root level script file. 
 If you choose to not use a single script entry point but use a directory of .sql scripts then there needs to be some way of ordering them (numerically or alphabetically).  It would also be ideal to have a way to track which files have been executed successfully and also the ability to mark scripts as re-runnable or run-once.  There are cases when you want to deploy a one-time data fix and there are cases when you always want to run a script.  This obviously would be moot if calling a third party tool.

> I'm still undecided on this one though. There's a conceptual mismatch here: previously Skeema uses *.sql files just to contain CREATE statements, which are declarative. But write queries are more imperative. They would need to be run on every skeema push, and it would be the user's responsibility to ensure they're only mapped in for the correct environments, and ensuring the queries are doing the correct conflict resolution for adjusting existing rows when needed.

This is where the execution tracking comes in.  My typical use case for pre/post deployment scripts is seed data and data fixes but I've used them for handling DDL changes that the tool could not handle (either unsupported or the generated change script was not ideal for the situation).  For example, if the tool didn't support a certain type of change I would make the change in a pre-deployment script and just modify the declarative SQL to look like the expected result so once it got to that point the change was already made and no declarative changes were auto-generated.  So being able to support any type of script is useful, even if the pre/post deployment hooks are _intended_ to be used for only DML (seed data / data fixes)

I hope this was helpful / useful in guiding the direction of this feature.

**Comment by evanelias** [comment] 2020-12-02 17:58
Good feedback, thanks! Hope to add the very initial support for hooks in the not-too-distant future. One other likely path is the notion of lower-level plumbing commands, allowing users to build custom automation out of smaller pieces of `skeema push`'s behavior.

**Comment by arlyon** [comment] 2021-04-15 18:16
I would like to chime in and mention django who specifically handle 'preload some data into the database for me' with Fixtures: https://docs.djangoproject.com/en/3.1/howto/initial-data/

These can be declared in a few formats (json, yaml, possibly more) and are checked against the schema for correctness before being turned into sql statements and batch loaded in.

**Comment by evanelias** [comment] 2021-04-15 19:37
As this issue is now 3 years old and getting quite long, there are a few different topics in this thread that I would like to clarify.

First, there are 4 core design principles behind Skeema that probably won't ever change, at least in the core CLI:

1. Skeema is *declarative*. Your *.sql files express the *desired state* and the tool does the work of figuring out how to reach that state.
2. Skeema uses *pure SQL* to express desired state, with the only exception being MySQL-cnf-file-like ini to express configuration. No use of YAML, JSON, TOML, or similar. This allows Skeema to interact seamlessly with other tools and clients that expect to deal with SQL. It also allows Skeema to be instantly accessible to engineers with familiarity to SQL.
3. The Skeema CLI is *stateless*. It does not rely on tracking state of "what has been applied", and instead introspects this information from each database it interacts with. This allows Skeema to seamlessly handle shard drift and environment drift.
4. Skeema is designed to work with database fleets of *any size* -- from small single-DB startups to massive sharded environments. Larger environments may need extra configuration (e.g. OSC tools and sharding) but the core functionality should all still be usable.

Some of these design principles are at odds with built-in support for DML. Complicating matters further, the DML use-cases differ substantially between companies:

A) Some just want DML for *seed data* (this original issue), meaning either "initial data for a new table" and/or "initial data for a new environment". This is fairly straightforward if the "new" part is respected strictly. But it's trickier if later changes to the seed data should also affect existing tables/environments, which it probably should, given user expectation. The tool would need to diff this data, or only allow idempotent DML (INSERT IGNORE or INSERT...ON DUPLICATE KEY UPDATE), and there are some performance considerations either way.

B) Some want DML for *data migrations* more generally. This requires stateful tracking of what has been executed. No other reasonable way around that, as far as I can think.

C) Some don't need built-in DML support at all, in any form, because they already have existing custom data migration tooling and/or dev environment setup tooling. Most of the largest MySQL users fall into this category, since their seed/data migration logic needs to account for sharding (which shards to route the DML to), prevention of replication lag (breaking up DML into smaller batches), and so forth.

Support for pre/post push hook points would essentially handle all three cases, by virtue of being flexible enough to support whatever you need. e.g. you could use django or some other tool just for seed data if you want. The only part I'm not clear on is the *granularity* required for these hooks, in terms of per-table/schema/directory/instance/invocation. Some previous discussion in this thread requested only per-`skeema`-invocation hooks, but thinking about that further, I'm not really clear on that need; you could always just wrap Skeema in some other script containing pre/post logic already. So overall this is an area where more community feedback is helpful.

Built-in support for use-case (A) might eventually make an appearance inside Skeema itself. But as mentioned a couple years ago, if this is going into the community (open source) edition of the Skeema CLI, it would almost certainly require corporate sponsorship in the low to mid 5 figure range. There's just no other way this is feasible, as it would require many weeks of fulltime work. Alternatively, it might end up in the commercial editions some day.

I have some ideas for how to eventually handle use-case (B), but that will definitely be outside of the core Skeema CLI, since it requires stateful tracking. It's much longer-term, in any case.

Hope this helps clarify the situation. In terms of community feedback, the most helpful thing is *use-case specifics* rather than technical implementation ideas. In other words: are there situations that don't fall into (A), (B), or (C)? If we end up going with the hook support as a first step, what granularity of hooks do you need?

**Comment by seanmacisaac** [comment] 2021-08-05 18:23
I'd also like this feature.  In terms of use cases, there are 2 broadly that I have:

1. Data that "is" schema.  i.e. lookup values that are referenced by ID from other tables, have equivalents in code, etc.  For this type of data the tables post a push should be exactly as it is declaratively in source control.  The size of this data is typically very small.  Just like with other DDL changes if you want to make a backwards incompatible change (say, deleting a row) you'd probably have to do it multiple commits/pushes/deploys, but if you did delete a row skeema should try and delete on push too if you specify --allow-unsafe.

2. Seed data for engineers for from scratch builds of the database on their local machines.  This is a lot easier to do as separate scripts, doesn't have production implications, and we have other solutions for it like just copy the data from our shared pre production environments.  If you did have a way of handling this I can see some advantages to putting this data close to the schema too, but once again, not a huge deal.

**Comment by evanelias** [comment] 2023-04-10 21:20
Initial support for seed data is finally landing as a premium feature in Skeema v1.10.0, due out within the next few weeks! This includes support for conditionally executing INSERT statements during `skeema push`, as well as the ability to dump data into INSERTs in *.sql files during `skeema pull` (sort of like a dynamically-updatable `mysqldump`).

#### Executing INSERTs in `skeema push`

The new `inserts` option controls how `skeema diff` and `skeema push` should interact with INSERT statements that are present in your *.sql files. With the default setting, `inserts=seed`, INSERT statements will be executed by `skeema push` only if the target table is empty. (Similarly, `skeema diff` will *display* the INSERT statement in this case, but not run it.) This is useful for populating new production tables that immediately need data, or populating a new environment (e.g. dev or CI) where all tables need some initial testing data set.

Other settings include `inserts=none` (ignore all INSERTs entirely) and `inserts=all` (run all INSERTs regardless of whether the tables are empty).

Skeema does not contain any functionality for diffing *data*, so `inserts=all` requires careful use of either INSERT IGNORE or INSERT...ON DUPLICATE KEY UPDATE to ensure insert statements are safe to re-run multiple times.

#### Dumping row data into INSERTs in `skeema pull`

The new `update-seed-inserts` boolean option controls the ability for `skeema pull` to look for specially-named views for creating or updating INSERT statements in your *.sql files. It is designed to handle these use-cases:

* Using a **subset of production data** for seed data:
  * Enable `update-seed-inserts` in the `[production]` section of .skeema files, so that `skeema pull production` refreshes your seed INSERTs, whereas pulling from other environments leaves them as-is
  * For example, if you have a table called app_users, and you want your seed data for this table to consist of the first 100 ids from production data, you can simply put this view definition somewhere in your *.sql files: `CREATE VIEW _seed_app_users AS SELECT * FROM app_users WHERE user_id <= 100;`. Then, `skeema pull production` will convert the data exposed by this view into a statement `INSERT INTO app_users ...` and add it to app_users.sql, or update the contents of an existing INSERT statement if there's already one there.
  * The view logic is dynamic, meaning `SELECT *` will expand to the current column list at the time of `skeema pull` -- so even as you ALTER the table to add columns, it's still easy to refresh the INSERT statements.
* Maintaining a **canonical set of seed data in one database environment**, such as considering the “staging” DB to be the source-of-truth for dumping seed data:
  * enable `update-seed-inserts` just in that environment section in a .skeema file.
  * In this case, typically each seed view will be of the simple form `CREATE VIEW _seed_foo AS SELECT * FROM foo` which dump the entirety of the table
* Updating seed data ad hoc: enable `update-seed-inserts` only on the command-line when needed, for example `skeema pull production --update-seed-inserts`

You can also maintain seed INSERTs manually, or use a custom pipeline / external tool (e.g. `mysqldump`), or mix-and-match these approaches as needed.

**Comment by evanelias** [comment] 2023-04-26 20:12
Skeema v1.10 has been [released](https://www.skeema.io/blog/2023/04/25/v1100-released/), and the Premium Edition of the CLI now includes seed data management functionality:

The new **[inserts](https://www.skeema.io/docs/options/#inserts)** option controls how `skeema push` should interact with INSERT statements that are present in your \*.sql files. With the default setting ([inserts=seed](https://www.skeema.io/docs/options/#inserts)) INSERT statements will be executed by `skeema push` only if the target table is empty. This is useful for populating new production tables that immediately need data, or providing fixture data for a dev/CI environment where tables need some initial testing data set.

Meanwhile, `skeema pull`'s new **[update-seed-inserts](https://www.skeema.io/docs/options/#update-seed-inserts)** option provides a way to automate creating or updating INSERT statements in your \*.sql files. By wrapping conditional dump logic in special "seed views" and then only enabling this option in a designated seed source environment, this feature provides fine-grained control over how, what, and where seed data is selectively dumped from.

🥳🎉💥 **Thank you to everyone who participated in this issue over the past five years!** 🙇 🙇 🙇
As a token of appreciation, new customers can use promotion code "issue22" to save $100 off your first payment of any [Skeema Premium CLI](https://www.skeema.io/download/) subscription. So for example if you sign up for a Skeema Plus monthly plan, your first month is only $24 USD with this discount code. All licenses are site licenses, meaning you just need one subscription for your entire company. Offer must be redeemed by June 30.

**Closed by evanelias** 2023-04-26 20:12 UTC
Labels: feature request, feedback wanted

**Comment by evanelias** [comment] 2023-06-15 21:10
Apologies for the slightly spammy comment, but I just wanted to post one last reminder about the "issue22" discount before the offer expires. Save $100 off your first payment of any [Skeema Premium CLI](https://www.skeema.io/download/) subscription plan by using the "issue22" promotion code on the checkout page before June 30.

Skeema Premium includes [seed data](https://www.skeema.io/docs/options/#inserts) support, along with tons of other features: [views](https://www.skeema.io/docs/requirements/#views-1), [triggers](https://www.skeema.io/docs/requirements/#triggers-1), [client-side SSL certs](https://www.skeema.io/docs/requirements/#ssl--tls-configuration), [SSH tunnels](https://www.skeema.io/docs/options/#ssh), [DEFINER stripping](https://www.skeema.io/docs/options/#strip-definer), [workspace offloading](https://www.skeema.io/docs/options/#temp-schema-environment), code-signed Windows CLI builds, secure Linux package manager repos, easy [self-update](https://www.skeema.io/docs/commands/update/) command, and more :)
