### ISSUE TITLE
skema lint: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by slisznia** [skeema/skeema#142] opened 2020-08-09 20:11 UTC
How to reproduce:

skeema --debug lint
2020-08-09 15:08:10 [INFO]  Linting dev/pc_school
2020-08-09 15:08:10 [DEBUG] goroutine 1 [running]:
                            runtime/debug.Stack(0xc0001bb8c0, 0x89724f, 0x5)
                            	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/debug/stack.go:24 +0x9d
                            main.main.func1(0xc00016ff58)
                            	/home/runner/work/skeema/skeema/skeema.go:37 +0x14d
                            panic(0x8167e0, 0xbdbfc0)
                            	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/panic.go:969 +0x166
                            github.com/skeema/tengo.(*Instance).CanSkipBinlog(0x0, 0x89df21)
                            	/home/runner/work/skeema/skeema/vendor/github.com/skeema/tengo/instance.go:269 +0x37
                            github.com/skeema/skeema/workspace.OptionsForDir(0xc000185050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                            	/home/runner/work/skeema/skeema/workspace/workspace.go:158 +0x38d
                            main.lintDir(0xc000185050, 0x4)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:144 +0xd79
                            main.lintWalker(0xc000185050, 0x5, 0xc0001bb8c0)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:92 +0xc4
                            main.LintHandler(0xc0001bb8c0, 0xc0001ce780, 0x898211)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:55 +0x7f
                            github.com/skeema/mybase.(*Config).HandleCommand(0xc0001bb8c0, 0x0, 0x0)
                            	/home/runner/work/skeema/skeema/vendor/github.com/skeema/mybase/config.go:88 +0x19d
                            main.main()
                            	/home/runner/work/skeema/skeema/skeema.go:53 +0xec
                            
2020-08-09 15:08:10 [ERROR] runtime error: invalid memory address or nil pointer dereference
2020-08-09 15:08:10 [DEBUG] Exit code 2

**Environment**
skeema version 1.4.5, commit 55f2c1b58bec6af7d40f6caa34911ed7f3e9b4d7, released 2020-07-27T21:21:38Z
DB: 10.4.13-MariaDB-1:10.4.13+maria~bionic-log mariadb.org binary distribution
OS: Ubuntu 18.04.4 LTS

**Comment by evanelias** [comment] 2020-08-09 21:03
Likely a duplicate of #141 -- does one of these situations apply to your use-case?

* There's no .skeema file at all, in this dir or its parent dirs
* There's a .skeema file but it doesn't ever define [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host)
* There's a .skeema file defining [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host), but not for the current environment name (e.g. it defines [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host) only under `[development]` but you're specifying a different environment name, or just running `skeema lint` which defaults to `production` environment)
* The [host-wrapper](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host-wrapper) option is in use, but the configured command returns an empty result for this directory

**Comment by slisznia** [comment] 2020-08-09 21:11
**You nailed it, the following condition reproduces the error:**

_There's a .skeema file defining host, but not for the current environment name (e.g. it defines host only under [development] but you're specifying a different environment name, or just running skeema lint which defaults to production environment)_

**Comment by evanelias** [comment] 2020-08-09 21:27
Excellent, closing this since it's already fixed in main branch, more background in #141

**Closed by evanelias** 2020-08-09 21:27 UTC
Labels: duplicate
